package serialize

import com.algolia.search.serialize.internal.Languages
import shouldEqual
import kotlin.test.Test

internal class TestLanguages {

    @Test
    fun test() {
        Languages.Afrikaans shouldEqual "af"
        Languages.Arabic shouldEqual "ar"
        Languages.Azeri shouldEqual "az"
        Languages.Bulgarian shouldEqual "bg"
        Languages.Brunei shouldEqual "bn"
        Languages.Catalan shouldEqual "ca"
        Languages.Czech shouldEqual "cs"
        Languages.Welsh shouldEqual "cy"
        Languages.Danish shouldEqual "da"
        Languages.German shouldEqual "de"
        Languages.English shouldEqual "en"
        Languages.Esperanto shouldEqual "eo"
        Languages.Spanish shouldEqual "es"
        Languages.Estonian shouldEqual "et"
        Languages.Basque shouldEqual "eu"
        Languages.Finnish shouldEqual "fi"
        Languages.Faroese shouldEqual "fo"
        Languages.French shouldEqual "fr"
        Languages.Galician shouldEqual "gl"
        Languages.Hebrew shouldEqual "he"
        Languages.Hindi shouldEqual "hi"
        Languages.Hungarian shouldEqual "hu"
        Languages.Armenian shouldEqual "hy"
        Languages.Indonesian shouldEqual "id"
        Languages.Icelandic shouldEqual "is"
        Languages.Italian shouldEqual "it"
        Languages.Japanese shouldEqual "ja"
        Languages.Georgian shouldEqual "ka"
        Languages.Kazakh shouldEqual "kk"
        Languages.Korean shouldEqual "ko"
        Languages.Kyrgyz shouldEqual "ky"
        Languages.Lithuanian shouldEqual "lt"
        Languages.Maori shouldEqual "mi"
        Languages.Mongolian shouldEqual "mn"
        Languages.Marathi shouldEqual "mr"
        Languages.Malay shouldEqual "ms"
        Languages.Maltese shouldEqual "mt"
        Languages.Norwegian shouldEqual "nb"
        Languages.Dutch shouldEqual "nl"
        Languages.NorthernSotho shouldEqual "ns"
        Languages.Polish shouldEqual "pl"
        Languages.Pashto shouldEqual "ps"
        Languages.Portuguese shouldEqual "pt"
        Languages.Quechua shouldEqual "qu"
        Languages.Romanian shouldEqual "ro"
        Languages.Russian shouldEqual "ru"
        Languages.Slovak shouldEqual "sk"
        Languages.Albanian shouldEqual "sq"
        Languages.Swedish shouldEqual "sv"
        Languages.Swahili shouldEqual "sw"
        Languages.Tamil shouldEqual "ta"
        Languages.Telugu shouldEqual "te"
        Languages.Tagalog shouldEqual "tl"
        Languages.Tswana shouldEqual "tn"
        Languages.Turkish shouldEqual "tr"
        Languages.Tatar shouldEqual "tt"
    }
}
