/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.abtesting

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * AbTestsVariant
 *
 * @param index Index name of the A/B test variant (case-sensitive).
 * @param trafficPercentage Percentage of search requests each variant receives.
 * @param description Description for this variant.
 */
@Serializable
public data class AbTestsVariant(

  /** Index name of the A/B test variant (case-sensitive). */
  @SerialName(value = "index") val index: String,

  /** Percentage of search requests each variant receives. */
  @SerialName(value = "trafficPercentage") val trafficPercentage: Int,

  /** Description for this variant. */
  @SerialName(value = "description") val description: String? = null,
) : AddABTestsVariant {}
