/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.abtesting

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Configuration of feature-based filters applied to the A/B test population.
 *
 * @param dynamicReRanking Whether to apply Dynamic Re-Ranking feature filters.
 * @param aiPerso Whether to apply AI Personalization feature filters.
 * @param multiSignalRanking Whether to apply Multi-Signal Re-Ranking feature filters.
 */
@Serializable
public data class FeatureFilters(

  /** Whether to apply Dynamic Re-Ranking feature filters. */
  @SerialName(value = "dynamicReRanking") val dynamicReRanking: Boolean? = null,

  /** Whether to apply AI Personalization feature filters. */
  @SerialName(value = "aiPerso") val aiPerso: Boolean? = null,

  /** Whether to apply Multi-Signal Re-Ranking feature filters. */
  @SerialName(value = "multiSignalRanking") val multiSignalRanking: Boolean? = null,
) {}
