/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Catalog
 *
 * @param domains Catalog entries grouped by domain.
 */
@Serializable
public data class Catalog(

  /** Catalog entries grouped by domain. */
  @SerialName(value = "domains") val domains: Map<kotlin.String, DomainCatalog>
) {}
