/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Click position.
 *
 * @param position Range of positions in the search results, using the pattern `[start,end]`. For
 *   positions 11 and up, click events are summed over the specified range. `-1` indicates the end
 *   of the list of search results.
 * @param clickCount Number of times this search has been clicked at that position.
 */
@Serializable
public data class ClickPosition(

  /**
   * Range of positions in the search results, using the pattern `[start,end]`. For positions 11 and
   * up, click events are summed over the specified range. `-1` indicates the end of the list of
   * search results.
   */
  @SerialName(value = "position") val position: List<Int>? = null,

  /** Number of times this search has been clicked at that position. */
  @SerialName(value = "clickCount") val clickCount: Int? = null,
) {}
