/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * FilterDefinition
 *
 * @param kind Field to filter on. With no `operator`, the field must be boolean.
 * @param domain Domain the field belongs to.
 * @param `operator` Comparison operator applied to a filter field, one of: `=`, `!=`, `>`, `<`,
 *   `>=`, `<=`, `IN`, `TAG_TREE`, `CONTAINS`, `STARTS_WITH`, `CONTAINS_PREFIX`. Requires a
 *   `parameter` to carry the operand.
 * @param parameter
 */
@Serializable
public data class FilterDefinition(

  /** Field to filter on. With no `operator`, the field must be boolean. */
  @SerialName(value = "kind") val kind: String,

  /** Domain the field belongs to. */
  @SerialName(value = "domain") val domain: String? = null,

  /**
   * Comparison operator applied to a filter field, one of: `=`, `!=`, `>`, `<`, `>=`, `<=`, `IN`,
   * `TAG_TREE`, `CONTAINS`, `STARTS_WITH`, `CONTAINS_PREFIX`. Requires a `parameter` to carry the
   * operand.
   */
  @SerialName(value = "operator") val `operator`: String? = null,
  @SerialName(value = "parameter") val parameter: ParameterReference? = null,
) {}
