/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * GetClickThroughRateResponse
 *
 * @param rate Click-through rate: calculated as the number of tracked searches with at least one
 *   click event divided by the number of tracked searches. If null, Algolia didn't receive any
 *   search requests with `clickAnalytics` set to true.
 * @param clickCount Number of clicks associated with this search.
 * @param trackedSearchCount Number of tracked searches. Tracked searches are search requests where
 *   the `clickAnalytics` parameter is true.
 * @param dates Daily click-through rates.
 */
@Serializable
public data class GetClickThroughRateResponse(

  /**
   * Click-through rate: calculated as the number of tracked searches with at least one click event
   * divided by the number of tracked searches. If null, Algolia didn't receive any search requests
   * with `clickAnalytics` set to true.
   */
  @SerialName(value = "rate") val rate: Double,

  /** Number of clicks associated with this search. */
  @SerialName(value = "clickCount") val clickCount: Int,

  /**
   * Number of tracked searches. Tracked searches are search requests where the `clickAnalytics`
   * parameter is true.
   */
  @SerialName(value = "trackedSearchCount") val trackedSearchCount: Int,

  /** Daily click-through rates. */
  @SerialName(value = "dates") val dates: List<DailyClickThroughRates>,
) {}
