/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.analytics

import kotlinx.serialization.*

/**
 * Character that characterizes how the filter is applied.  For example, for a facet filter `facet:value`, `:` is the operator. For a numeric filter `count>50`, `>` is the operator.
 */
@Serializable
public enum class Operator(public val value: kotlin.String) {

  @SerialName(value = ":")
  Colon(":"),

  @SerialName(value = "<")
  LessThan("<"),

  @SerialName(value = "<=")
  LessThanEqual("<="),

  @SerialName(value = "=")
  Equal("="),

  @SerialName(value = "!=")
  ExclamationEqual("!="),

  @SerialName(value = ">")
  GreaterThan(">"),

  @SerialName(value = ">=")
  GreaterThanEqual(">=");

  override fun toString(): kotlin.String = value
}
