/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * OrderDefinition
 *
 * @param kind Field to sort by. Must appear in `metrics` or `groupBy`.
 * @param direction
 * @param domain Domain the field belongs to.
 */
@Serializable
public data class OrderDefinition(

  /** Field to sort by. Must appear in `metrics` or `groupBy`. */
  @SerialName(value = "kind") val kind: String,
  @SerialName(value = "direction") val direction: OrderDirection,

  /** Domain the field belongs to. */
  @SerialName(value = "domain") val domain: String? = null,
) {}
