/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * Literal value. Its JSON type depends on `kind` (array of strings for `indices`, string for dates,
 * tags, and country, number for numeric operands, and so on).
 *
 * Implementations:
 * - [Boolean] - *[ParameterValue.of]*
 * - [Double] - *[ParameterValue.of]*
 * - [List<String>] - *[ParameterValue.of]*
 * - [String] - *[ParameterValue.of]*
 */
@Serializable(ParameterValueSerializer::class)
public sealed interface ParameterValue {
  @Serializable @JvmInline public value class StringValue(public val value: String) : ParameterValue

  @Serializable @JvmInline public value class DoubleValue(public val value: Double) : ParameterValue

  @Serializable
  @JvmInline
  public value class ListOfStringValue(public val value: List<String>) : ParameterValue

  @Serializable
  @JvmInline
  public value class BooleanValue(public val value: Boolean) : ParameterValue

  public companion object {

    public fun of(value: String): ParameterValue = StringValue(value)

    public fun of(value: Double): ParameterValue = DoubleValue(value)

    public fun of(value: List<String>): ParameterValue = ListOfStringValue(value)

    public fun of(value: Boolean): ParameterValue = BooleanValue(value)
  }
}

internal class ParameterValueSerializer :
  JsonContentPolymorphicSerializer<ParameterValue>(ParameterValue::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<ParameterValue> {
    return when {
      element.isString -> ParameterValue.StringValue.serializer()
      element.isDouble -> ParameterValue.DoubleValue.serializer()
      element is JsonArray -> ParameterValue.ListOfStringValue.serializer()
      element.isBoolean -> ParameterValue.BooleanValue.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
