/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ParameterDefinition
 *
 * @param kind Parameter identifier, for example `indices`, `startDate`, `endDate`, `tags`, or
 *   `country`.
 * @param `value`
 * @param domain Domain the parameter belongs to.
 */
@Serializable
public data class ParameterDefinition(

  /** Parameter identifier, for example `indices`, `startDate`, `endDate`, `tags`, or `country`. */
  @SerialName(value = "kind") val kind: String,
  @SerialName(value = "value") val `value`: ParameterValue,

  /** Domain the parameter belongs to. */
  @SerialName(value = "domain") val domain: String? = null,
) {}
