/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ScalarPayload
 *
 * @param metrics Fields to aggregate.
 * @param parameters Literal values referenced by the query.
 * @param domain Default domain propagated to entries that omit their own.
 * @param filters Filter conditions.
 */
@Serializable
public data class ScalarPayload(

  /** Fields to aggregate. */
  @SerialName(value = "metrics") val metrics: List<FieldReference>,

  /** Literal values referenced by the query. */
  @SerialName(value = "parameters") val parameters: List<ParameterDefinition>,

  /** Default domain propagated to entries that omit their own. */
  @SerialName(value = "domain") val domain: String? = null,

  /** Filter conditions. */
  @SerialName(value = "filters") val filters: List<FilterDefinition>? = null,
) {}
