/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * SeriesDate
 *
 * @param date Day, formatted as YYYY-MM-DD.
 * @param metrics Metric values for the day.
 */
@Serializable
public data class SeriesDate(

  /** Day, formatted as YYYY-MM-DD. */
  @SerialName(value = "date") val date: String,

  /** Metric values for the day. */
  @SerialName(value = "metrics") val metrics: JsonObject,
) {}
