/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TimeseriesPayload
 *
 * @param metrics Fields to aggregate.
 * @param parameters Literal values referenced by the query.
 * @param domain Default domain propagated to entries that omit their own.
 * @param groupBy Fields to split the series by.
 * @param filters Filter conditions.
 * @param limit Maximum number of series (groupBy values) to return.
 * @param offset Number of series to skip.
 */
@Serializable
public data class TimeseriesPayload(

  /** Fields to aggregate. */
  @SerialName(value = "metrics") val metrics: List<FieldReference>,

  /** Literal values referenced by the query. */
  @SerialName(value = "parameters") val parameters: List<ParameterDefinition>,

  /** Default domain propagated to entries that omit their own. */
  @SerialName(value = "domain") val domain: String? = null,

  /** Fields to split the series by. */
  @SerialName(value = "groupBy") val groupBy: List<FieldReference>? = null,

  /** Filter conditions. */
  @SerialName(value = "filters") val filters: List<FilterDefinition>? = null,

  /** Maximum number of series (groupBy values) to return. */
  @SerialName(value = "limit") val limit: Int? = null,

  /** Number of series to skip. */
  @SerialName(value = "offset") val offset: Int? = null,
) {}
