/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TimeseriesResponse
 *
 * @param series One entry per `groupBy` combination. `null` when the query matched no data.
 */
@Serializable
public data class TimeseriesResponse(

  /** One entry per `groupBy` combination. `null` when the query matched no data. */
  @SerialName(value = "series") val series: List<Series>? = null
) {}
