/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TopSearchesResponse
 *
 * @param searches Most popular searches and their number of search results (hits).
 */
@Serializable
public data class TopSearchesResponse(

  /** Most popular searches and their number of search results (hits). */
  @SerialName(value = "searches") val searches: List<TopSearch>
) : GetTopSearchesResponse {}
