/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TopSearch
 *
 * @param search Search query.
 * @param count Number of searches.
 * @param nbHits Number of results (hits).
 */
@Serializable
public data class TopSearch(

  /** Search query. */
  @SerialName(value = "search") val search: String,

  /** Number of searches. */
  @SerialName(value = "count") val count: Int,

  /** Number of results (hits). */
  @SerialName(value = "nbHits") val nbHits: Int,
)
