/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.abtestingv3

import kotlinx.serialization.*

/**
 * Sort order for A/B tests by start date. Use 'asc' for ascending or 'desc' for descending. Active
 * A/B tests are always listed first.
 */
@Serializable
public enum class Direction(public val value: kotlin.String) {

  @SerialName(value = "asc") Asc("asc"),
  @SerialName(value = "desc") Desc("desc");

  override fun toString(): kotlin.String = value
}
