/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.abtestingv3

import kotlinx.serialization.*

/**
 * Multiple-testing correction method applied when evaluating metric significance.
 */
@Serializable
public enum class ErrorCorrectionType(public val value: kotlin.String) {

  @SerialName(value = "bonferroni")
  Bonferroni("bonferroni"),

  @SerialName(value = "benjamini-hochberg")
  BenjaminiHochberg("benjamini-hochberg");

  override fun toString(): kotlin.String = value
}
