/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.abtestingv3

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * EstimateABTestResponse
 *
 * @param durationDays Estimated number of days needed to reach the sample sizes required for
 *   detecting the configured effect. This value is based on historical traffic.
 * @param sampleSizes Sample size estimates for each variant. The first element is the control
 *   variant. Each element is the estimated number of searches required to achieve the desired
 *   statistical significance.
 */
@Serializable
public data class EstimateABTestResponse(

  /**
   * Estimated number of days needed to reach the sample sizes required for detecting the configured
   * effect. This value is based on historical traffic.
   */
  @SerialName(value = "durationDays") val durationDays: Long? = null,

  /**
   * Sample size estimates for each variant. The first element is the control variant. Each element
   * is the estimated number of searches required to achieve the desired statistical significance.
   */
  @SerialName(value = "sampleSizes") val sampleSizes: List<Long>? = null,
) {}
