/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.abtestingv3

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * A/B test configuration for estimating the sample size and duration using minimum detectable
 * effect.
 *
 * @param minimumDetectableEffect
 * @param filters List of metric filters applied to the test population.
 */
@Serializable
public data class EstimateConfiguration(
  @SerialName(value = "minimumDetectableEffect")
  val minimumDetectableEffect: MinimumDetectableEffect,

  /** List of metric filters applied to the test population. */
  @SerialName(value = "filters") val filters: List<MetricsFilter>? = null,
) {}
