/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.abtestingv3

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * MetricDate
 *
 * @param date Date where the metric was updated, in RFC 3339 format.
 * @param metrics All ABTest metrics that were defined during test creation.
 */
@Serializable
public data class MetricDate(

  /** Date where the metric was updated, in RFC 3339 format. */
  @SerialName(value = "date") val date: String? = null,

  /** All ABTest metrics that were defined during test creation. */
  @SerialName(value = "metrics") val metrics: List<MetricResult>? = null,
)
