package com.algolia.search.serialize

public const val RouteIndexesV1: String = "1/indexes"
public const val RouteSettings: String = "settings"
public const val RouteClustersV1: String = "1/clusters"
public const val RouteSynonyms: String = "synonyms"
public const val RouteEventsV1: String = "1/events"
public const val RouteABTestsV2: String = "2/abtests"
public const val RouteRules: String = "rules"
public const val RouteKeysV1: String = "1/keys"
public const val RouteLogs: String = "1/logs"
public const val RouteRecommendation: String = "1/recommendation"
public const val RouteRecommendationV2: String = "1/strategies/personalization"
public const val RoutePlaces: String = "1/places"
public const val RouteDictionaries: String = "1/dictionaries"
