/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Composition
 *
 * @param objectID Composition unique identifier.
 * @param name Composition name.
 * @param behavior
 * @param description Composition description.
 */
@Serializable
public data class Composition(

  /** Composition unique identifier. */
  @SerialName(value = "objectID") val objectID: String,

  /** Composition name. */
  @SerialName(value = "name") val name: String,
  @SerialName(value = "behavior") val behavior: CompositionBehavior,

  /** Composition description. */
  @SerialName(value = "description") val description: String? = null,
) : BatchCompositionAction {}
