/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * An object containing a `multifeed` behavior.
 *
 * @param multifeed
 */
@Serializable
public data class CompositionMultifeedBehavior(
  @SerialName(value = "multifeed") val multifeed: Multifeed
) : CompositionBehavior {}
