/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Composition
 *
 * @param objectID Composition unique identifier.
 * @param name Composition name.
 * @param behavior
 * @param description Composition description.
 * @param sortingStrategy A mapping of sorting labels to the indices (or replicas) that implement
 *   those sorting rules. The sorting indices MUST be related to the associated main targeted index
 *   in the composition. Each key is the label your frontend sends at runtime (for example, \"Price
 *   (asc)\"), and each value is the name of the index that should be queried when that label is
 *   selected. When a request includes a \"sortBy\" parameter, the platform looks up the
 *   corresponding index in this mapping and uses it to execute the query. The main targeted index
 *   is replaced with the sorting strategy index it is mapped to. Up to 20 sorting strategies can be
 *   defined.
 */
@Serializable
public data class Composition(

  /** Composition unique identifier. */
  @SerialName(value = "objectID") val objectID: String,

  /** Composition name. */
  @SerialName(value = "name") val name: String,
  @SerialName(value = "behavior") val behavior: CompositionBehavior,

  /** Composition description. */
  @SerialName(value = "description") val description: String? = null,

  /**
   * A mapping of sorting labels to the indices (or replicas) that implement those sorting rules.
   * The sorting indices MUST be related to the associated main targeted index in the composition.
   * Each key is the label your frontend sends at runtime (for example, \"Price (asc)\"), and each
   * value is the name of the index that should be queried when that label is selected. When a
   * request includes a \"sortBy\" parameter, the platform looks up the corresponding index in this
   * mapping and uses it to execute the query. The main targeted index is replaced with the sorting
   * strategy index it is mapped to. Up to 20 sorting strategies can be defined.
   */
  @SerialName(value = "sortingStrategy") val sortingStrategy: Map<kotlin.String, String>? = null,
) : BatchCompositionAction {}
