/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*

/**
 * Deduplication positioning configures how a duplicate result should be resolved between an
 * injected item and main search results. Current configuration supports: - 'highest': always select
 * the item in the highest position, and remove duplicates that appear lower in the results. -
 * 'highestInjected': duplicate result will be moved to its highest possible injected position, but
 * not higher. If a duplicate appears higher in main search results, it will be removed to stay it's
 * intended group position (which could be lower than main).
 */
@Serializable
public enum class DedupPositioning(public val value: kotlin.String) {

  @SerialName(value = "highest") Highest("highest"),
  @SerialName(value = "highestInjected") HighestInjected("highestInjected");

  override fun toString(): kotlin.String = value
}
