/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Operation arguments when deleting.
 *
 * @param objectID Composition unique identifier.
 */
@Serializable
public data class DeleteCompositionAction(

  /** Composition unique identifier. */
  @SerialName(value = "objectID") val objectID: String,
) : BatchCompositionAction
