/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * External
 *
 * @param index Composition Index name.
 * @param params
 * @param ordering
 */
@Serializable
public data class External(

  /** Composition Index name. */
  @SerialName(value = "index") val index: String,

  @SerialName(value = "params") val params: BaseInjectionQueryParameters? = null,

  @SerialName(value = "ordering") val ordering: ExternalOrdering? = null,
)
