/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ExternalProvider
 *
 * @param configurationParams Values for non-prefixed configuration placeholders, overriding the
 *   composition source's `configurationParams` and the configuration's `defaults`.
 */
@Serializable
public data class ExternalProvider(

  /**
   * Values for non-prefixed configuration placeholders, overriding the composition source's
   * `configurationParams` and the configuration's `defaults`.
   */
  @SerialName(value = "configurationParams") val configurationParams: JsonObject? = null
) {}
