/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Order of facet names.
 *
 * @param order Explicit order of facets or facet values.  This setting lets you always show specific facets or facet values at the top of the list.
 */
@Serializable
public data class Facets(

  /** Explicit order of facets or facet values.  This setting lets you always show specific facets or facet values at the top of the list.  */
  @SerialName(value = "order") val order: List<String>? = null,
)
