/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.composition

import com.algolia.client.extensions.internal.*
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * An object that contains the extra key-value pairs provided in the injectedItem definition.
 *
 * @param injectedItemKey The key of the injectedItem that inserted this metadata.
 */
@Serializable(HitMetadataSerializer::class)
public data class HitMetadata(

  /** The key of the injectedItem that inserted this metadata. */
  val injectedItemKey: String? = null,

  val additionalProperties: Map<String, JsonElement>? = null,
)

internal object HitMetadataSerializer : KSerializer<HitMetadata> {

  override val descriptor: SerialDescriptor = buildClassSerialDescriptor("HitMetadata") {
    element<String>("_injectedItemKey", isOptional = true)
  }

  override fun deserialize(decoder: Decoder): HitMetadata {
    val input = decoder.asJsonDecoder()
    val tree = input.decodeJsonObject()
    return HitMetadata(
      injectedItemKey = tree["_injectedItemKey"]?.let { input.json.decodeFromJsonElement(it) },
      additionalProperties = tree.filterKeys { it !in descriptor.elementNames },
    )
  }

  override fun serialize(encoder: Encoder, value: HitMetadata) {
    val output = encoder.asJsonEncoder()
    val json = buildJsonObject {
      value.injectedItemKey?.let { put("_injectedItemKey", output.json.encodeToJsonElement(it)) }
      value.additionalProperties?.onEach { (key, element) -> put(key, element) }
    }
    (encoder as JsonEncoder).encodeJsonElement(json)
  }
}
