/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * InjectedItemExternal
 *
 * @param index Algolia index used to retrieve records.
 * @param ordering
 * @param params
 */
@Serializable
public data class InjectedItemExternal(

  /** Algolia index used to retrieve records. */
  @SerialName(value = "index") val index: String,
  @SerialName(value = "ordering") val ordering: ExternalOrdering? = null,
  @SerialName(value = "params") val params: BaseInjectionQueryParameters? = null,
) {}
