/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Injected items will originate from a recommendation request performed on the specified index.
 *
 * @param recommend
 */
@Serializable
public data class InjectedItemRecommendSource(
  @SerialName(value = "recommend") val recommend: Recommend
) : InjectedItemSource {}
