/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * InjectedItem
 *
 * @param key injected Item unique identifier.
 * @param source
 * @param position
 * @param length
 * @param metadata
 */
@Serializable
public data class InjectedItem(

  /** injected Item unique identifier. */
  @SerialName(value = "key") val key: String,
  @SerialName(value = "source") val source: InjectedItemSource,
  @SerialName(value = "position") val position: Int,
  @SerialName(value = "length") val length: Int,
  @SerialName(value = "metadata") val metadata: InjectedItemMetadata? = null,
) {}
