/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ListCompositionsResponse
 *
 * @param items All compositions in your Algolia application.
 * @param nbPages Number of pages.
 * @param page Current page.
 * @param hitsPerPage Number of items per page.
 * @param nbHits Number of items.
 */
@Serializable
public data class ListCompositionsResponse(

  /** All compositions in your Algolia application. */
  @SerialName(value = "items") val items: List<Composition>,

  /** Number of pages. */
  @SerialName(value = "nbPages") val nbPages: Int,

  /** Current page. */
  @SerialName(value = "page") val page: Int,

  /** Number of items per page. */
  @SerialName(value = "hitsPerPage") val hitsPerPage: Int,

  /** Number of items. */
  @SerialName(value = "nbHits") val nbHits: Int,
)
