/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * MultipleBatchResponse
 *
 * @param taskID Task IDs. One for each index.
 */
@Serializable
public data class MultipleBatchResponse(

  /** Task IDs. One for each index. */
  @SerialName(value = "taskID") val taskID: Map<kotlin.String, Long>
) {}
