/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Multifeed
 *
 * @param feeds A key-value store of Feed ID to Feed. Currently, the only supported Feed type is an
 *   Injection.
 * @param feedsOrder A list of Feed IDs that specifies the order in which to order the results in
 *   the response. The IDs should be a subset of those in the Feeds object, and only those specified
 *   will be processed. When this field is not set, all Feeds are processed and returned with a
 *   default ordering.
 */
@Serializable
public data class Multifeed(

  /**
   * A key-value store of Feed ID to Feed. Currently, the only supported Feed type is an Injection.
   */
  @SerialName(value = "feeds") val feeds: Map<kotlin.String, FeedInjection>,

  /**
   * A list of Feed IDs that specifies the order in which to order the results in the response. The
   * IDs should be a subset of those in the Feeds object, and only those specified will be
   * processed. When this field is not set, all Feeds are processed and returned with a default
   * ordering.
   */
  @SerialName(value = "feedsOrder") val feedsOrder: List<String>? = null,
) {}
