/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Dynamic configuration for testing agents.
 *
 * @param instructions
 * @param config
 * @param tools
 * @param id
 * @param providerId
 * @param model
 * @param systemPrompt
 */
@Serializable
public data class AgentTestConfiguration(
  @SerialName(value = "instructions") val instructions: String,
  @SerialName(value = "config") val config: JsonObject,
  @SerialName(value = "tools") val tools: List<ToolConfigInput>,
  @SerialName(value = "id") val id: String? = null,
  @SerialName(value = "providerId") val providerId: String? = null,
  @SerialName(value = "model") val model: String? = null,
  @SerialName(value = "systemPrompt") val systemPrompt: String? = null,
) {}
