/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * AgentCompletionRequestUnion
 *
 * Implementations:
 * - [AgentCompletionRequest]
 * - [AguiCompletionRequest]
 */
@Serializable(AgentCompletionRequestUnionSerializer::class)
public sealed interface AgentCompletionRequestUnion {
  @Serializable
  @JvmInline
  public value class AguiCompletionRequestValue(public val value: AguiCompletionRequest) :
    AgentCompletionRequestUnion

  @Serializable
  @JvmInline
  public value class AgentCompletionRequestValue(public val value: AgentCompletionRequest) :
    AgentCompletionRequestUnion

  public companion object {

    public fun of(value: AguiCompletionRequest): AgentCompletionRequestUnion =
      AguiCompletionRequestValue(value)

    public fun of(value: AgentCompletionRequest): AgentCompletionRequestUnion =
      AgentCompletionRequestValue(value)
  }
}

internal class AgentCompletionRequestUnionSerializer :
  JsonContentPolymorphicSerializer<AgentCompletionRequestUnion>(
    AgentCompletionRequestUnion::class
  ) {
  override fun selectDeserializer(
    element: JsonElement
  ): DeserializationStrategy<AgentCompletionRequestUnion> {
    return when {
      element is JsonObject &&
        element.containsKey("messages") &&
        element.containsKey("runId") &&
        element.containsKey("threadId") -> AguiCompletionRequest.serializer()
      element is JsonObject -> AgentCompletionRequest.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
