/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Configuration for the Algolia Recommend tool. Allows specifying recommend models and related
 * parameters.
 *
 * @param name
 * @param type
 * @param allowedConfigs
 * @param predefinedRecommendParameters
 */
@Serializable
public data class AlgoliaRecommendToolConfigInput(
  @SerialName(value = "name") val name: String,
  @SerialName(value = "type") val type: String,
  @SerialName(value = "allowedConfigs")
  val allowedConfigs: List<AlgoliaRecommendToolIndexConfig>? = null,
  @SerialName(value = "predefinedRecommendParameters")
  val predefinedRecommendParameters: JsonObject? = null,
) : ToolConfigInput {}
