/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Configuration for the algolia_grouped_results tool.
 *
 * @param type
 * @param name
 * @param isTerminal When true, a successful tool invocation ends the agent graph (no further LLM
 *   turn). Use for chat experiences where the tool payload IS the final response. Leave false to
 *   let the main LLM produce a concluding assistant message after the tool runs.
 * @param minGroups Minimum number of result groups.
 * @param maxGroups Maximum number of result groups.
 * @param minResultsPerGroup Minimum hits per group.
 * @param maxResultsPerGroup Maximum hits per group.
 */
@Serializable
public data class AlgoliaGroupedResultsToolConfig(
  @SerialName(value = "type") val type: String,
  @SerialName(value = "name") val name: String? = null,

  /**
   * When true, a successful tool invocation ends the agent graph (no further LLM turn). Use for
   * chat experiences where the tool payload IS the final response. Leave false to let the main LLM
   * produce a concluding assistant message after the tool runs.
   */
  @SerialName(value = "isTerminal") val isTerminal: Boolean? = null,

  /** Minimum number of result groups. */
  @SerialName(value = "minGroups") val minGroups: Int? = null,

  /** Maximum number of result groups. */
  @SerialName(value = "maxGroups") val maxGroups: Int? = null,

  /** Minimum hits per group. */
  @SerialName(value = "minResultsPerGroup") val minResultsPerGroup: Int? = null,

  /** Maximum hits per group. */
  @SerialName(value = "maxResultsPerGroup") val maxResultsPerGroup: Int? = null,
) : ItemsUnion {}
