/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Request body for bulk insert.
 *
 * @param domains List of domain patterns to add.
 */
@Serializable
public data class AllowedDomainBulkInsert(

  /** List of domain patterns to add. */
  @SerialName(value = "domains") val domains: List<String>
) {}
