/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Anthropic-specific provider input.
 *
 * @param apiKey
 * @param baseUrl
 */
@Serializable
public data class AnthropicProviderInput(
  @SerialName(value = "apiKey") val apiKey: String,
  @SerialName(value = "baseUrl") val baseUrl: String? = null,
) : ProviderInputNullable, ProviderInput {}
