/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * AroundPrecisionUnion
 *
 * Implementations:
 * - [Int] - *[AroundPrecisionUnion.of]*
 * - [List<Map<kotlin.String, Int>>] - *[AroundPrecisionUnion.of]*
 */
@Serializable(AroundPrecisionUnionSerializer::class)
public sealed interface AroundPrecisionUnion {
  @Serializable @JvmInline public value class IntValue(public val value: Int) : AroundPrecisionUnion

  @Serializable
  @JvmInline
  public value class ListOfMapOfkotlinStringIntValue(
    public val value: List<Map<kotlin.String, Int>>
  ) : AroundPrecisionUnion

  public companion object {

    public fun of(value: Int): AroundPrecisionUnion = IntValue(value)

    public fun of(value: List<Map<kotlin.String, Int>>): AroundPrecisionUnion =
      ListOfMapOfkotlinStringIntValue(value)
  }
}

internal class AroundPrecisionUnionSerializer :
  JsonContentPolymorphicSerializer<AroundPrecisionUnion>(AroundPrecisionUnion::class) {
  override fun selectDeserializer(
    element: JsonElement
  ): DeserializationStrategy<AroundPrecisionUnion> {
    return when {
      element.isInt -> AroundPrecisionUnion.IntValue.serializer()
      element is JsonArray -> AroundPrecisionUnion.ListOfMapOfkotlinStringIntValue.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
