/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * AssistantPartV4
 *
 * Implementations:
 * - [ReasoningPartV4]
 * - [StepStartPartV4]
 * - [TextPartV4]
 * - [ToolInvocationPartV4]
 */
@Serializable(AssistantPartV4Serializer::class)
public sealed interface AssistantPartV4 {
  @Serializable
  @JvmInline
  public value class ReasoningPartV4Value(public val value: ReasoningPartV4) : AssistantPartV4

  @Serializable
  @JvmInline
  public value class TextPartV4Value(public val value: TextPartV4) : AssistantPartV4

  @Serializable
  @JvmInline
  public value class ToolInvocationPartV4Value(public val value: ToolInvocationPartV4) :
    AssistantPartV4

  @Serializable
  @JvmInline
  public value class StepStartPartV4Value(public val value: StepStartPartV4) : AssistantPartV4

  public companion object {

    public fun of(value: ReasoningPartV4): AssistantPartV4 = ReasoningPartV4Value(value)

    public fun of(value: TextPartV4): AssistantPartV4 = TextPartV4Value(value)

    public fun of(value: ToolInvocationPartV4): AssistantPartV4 = ToolInvocationPartV4Value(value)

    public fun of(value: StepStartPartV4): AssistantPartV4 = StepStartPartV4Value(value)
  }
}

internal class AssistantPartV4Serializer :
  JsonContentPolymorphicSerializer<AssistantPartV4>(AssistantPartV4::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<AssistantPartV4> {
    return when {
      element is JsonObject && element.containsKey("reasoning") -> ReasoningPartV4.serializer()
      element is JsonObject && element.containsKey("text") -> TextPartV4.serializer()
      element is JsonObject && element.containsKey("toolInvocation") ->
        ToolInvocationPartV4.serializer()
      element is JsonObject -> StepStartPartV4.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
