/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * AssistantPartV5
 *
 * Implementations:
 * - [DataGuardrailViolationPartV5]
 * - [DataPartV5]
 * - [ReasoningPartV5]
 * - [StepStartPartV5]
 * - [TextPartV5]
 * - [ToolPartV5]
 */
@Serializable(AssistantPartV5Serializer::class)
public sealed interface AssistantPartV5 {
  @Serializable
  @JvmInline
  public value class DataGuardrailViolationPartV5Value(
    public val value: DataGuardrailViolationPartV5
  ) : AssistantPartV5

  @Serializable
  @JvmInline
  public value class ToolPartV5Value(public val value: ToolPartV5) : AssistantPartV5

  @Serializable
  @JvmInline
  public value class StepStartPartV5Value(public val value: StepStartPartV5) : AssistantPartV5

  @Serializable
  @JvmInline
  public value class TextPartV5Value(public val value: TextPartV5) : AssistantPartV5

  @Serializable
  @JvmInline
  public value class ReasoningPartV5Value(public val value: ReasoningPartV5) : AssistantPartV5

  @Serializable
  @JvmInline
  public value class DataPartV5Value(public val value: DataPartV5) : AssistantPartV5

  public companion object {

    public fun of(value: DataGuardrailViolationPartV5): AssistantPartV5 =
      DataGuardrailViolationPartV5Value(value)

    public fun of(value: ToolPartV5): AssistantPartV5 = ToolPartV5Value(value)

    public fun of(value: StepStartPartV5): AssistantPartV5 = StepStartPartV5Value(value)

    public fun of(value: TextPartV5): AssistantPartV5 = TextPartV5Value(value)

    public fun of(value: ReasoningPartV5): AssistantPartV5 = ReasoningPartV5Value(value)

    public fun of(value: DataPartV5): AssistantPartV5 = DataPartV5Value(value)
  }
}

internal class AssistantPartV5Serializer :
  JsonContentPolymorphicSerializer<AssistantPartV5>(AssistantPartV5::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<AssistantPartV5> {
    return when {
      element is JsonObject && element.containsKey("data") ->
        DataGuardrailViolationPartV5.serializer()
      element is JsonObject && element.containsKey("toolCallId") -> ToolPartV5.serializer()
      element is JsonObject -> StepStartPartV5.serializer()
      element is JsonObject -> TextPartV5.serializer()
      element is JsonObject -> ReasoningPartV5.serializer()
      element is JsonObject -> DataPartV5.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
