/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ClientToolsArgsSchema
 *
 * @param type
 * @param properties
 * @param required
 */
@Serializable
public data class ClientToolsArgsSchema(
  @SerialName(value = "type") val type: String? = null,
  @SerialName(value = "properties") val properties: JsonObject? = null,
  @SerialName(value = "required") val required: List<String>? = null,
) {}
