/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Deterministic trim request (no LLM calls).
 *
 * @param messages
 * @param keepLastMessages Keep only the last N messages, dropping older ones. Applied before the
 *   token budget.
 * @param maxTokensEstimate Drop oldest messages until the estimated token total fits this budget
 *   (heuristic).
 * @param dropToolParts Strip tool-invocation/result parts from the messages that are kept. Applied
 *   before the token budget, so the budget counts only surviving content.
 */
@Serializable
public data class ContextTrimRequest(
  @SerialName(value = "messages") val messages: MessagesUnion,

  /** Keep only the last N messages, dropping older ones. Applied before the token budget. */
  @SerialName(value = "keepLastMessages") val keepLastMessages: Int? = null,

  /** Drop oldest messages until the estimated token total fits this budget (heuristic). */
  @SerialName(value = "maxTokensEstimate") val maxTokensEstimate: Int? = null,

  /**
   * Strip tool-invocation/result parts from the messages that are kept. Applied before the token
   * budget, so the budget counts only surviving content.
   */
  @SerialName(value = "dropToolParts") val dropToolParts: Boolean? = null,
) {}
