/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Result of a context operation, ready to feed to ``/completions``.
 *
 * @param messages
 * @param stats
 * @param compaction
 */
@Serializable
public data class ContextResponse(
  @SerialName(value = "messages") val messages: MessagesUnion,
  @SerialName(value = "stats") val stats: ContextStats,
  @SerialName(value = "compaction") val compaction: CompactionStats? = null,
) {}
