/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Response model for a conversation with all its messages.
 *
 * @param id
 * @param agentId
 * @param createdAt
 * @param updatedAt
 * @param messages
 * @param title
 * @param lastActivityAt
 * @param userToken
 * @param isFromDashboard
 * @param messageCount
 * @param totalInputTokens
 * @param totalOutputTokens
 * @param totalTokens
 * @param conversationMetadata
 * @param feedback
 */
@Serializable
public data class ConversationFullResponse(
  @SerialName(value = "id") val id: String,
  @SerialName(value = "agentId") val agentId: String,
  @SerialName(value = "createdAt") val createdAt: String,
  @SerialName(value = "updatedAt") val updatedAt: String,
  @SerialName(value = "messages") val messages: List<MessageResponse>,
  @SerialName(value = "title") val title: String? = null,
  @SerialName(value = "lastActivityAt") val lastActivityAt: String? = null,
  @SerialName(value = "userToken") val userToken: String? = null,
  @SerialName(value = "isFromDashboard") val isFromDashboard: Boolean? = null,
  @SerialName(value = "messageCount") val messageCount: Int? = null,
  @SerialName(value = "totalInputTokens") val totalInputTokens: Int? = null,
  @SerialName(value = "totalOutputTokens") val totalOutputTokens: Int? = null,
  @SerialName(value = "totalTokens") val totalTokens: Int? = null,
  @SerialName(value = "conversationMetadata")
  val conversationMetadata: ConversationMetadata? = null,
  @SerialName(value = "feedback") val feedback: List<FeedbackResponse>? = null,
) {}
