/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * A ``data-guardrail-violation`` part that an AI SDK v5 client sends back. Send this part to tell
 * the completions endpoint that a guardrail blocked the previous turn.
 *
 * @param `data`
 * @param type
 */
@Serializable
public data class DataGuardrailViolationPartV5(
  @SerialName(value = "data") val `data`: GuardrailViolationDataV5,
  @SerialName(value = "type") val type: String? = null,
) : AssistantPartV5 {}
