/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Structured search parameters configuration for an Algolia index. Each parameter controls whether
 * it is exposed to the LLM, its default value, optional constraints, and merge behavior.
 *
 * @param query
 * @param hitsPerPage
 * @param page
 * @param attributesToRetrieve
 * @param responseFields
 * @param facets
 * @param custom
 */
@Serializable
public data class IndexSearchParameters(
  @SerialName(value = "query") val query: TextParam? = null,
  @SerialName(value = "hitsPerPage") val hitsPerPage: NumberParam? = null,
  @SerialName(value = "page") val page: NumberParam? = null,
  @SerialName(value = "attributesToRetrieve") val attributesToRetrieve: StringArrayParam? = null,
  @SerialName(value = "responseFields") val responseFields: StringArrayParam? = null,
  @SerialName(value = "facets") val facets: FacetsParam? = null,
  @SerialName(value = "custom") val custom: JsonObject? = null,
) {}
