/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * InputUnion
 *
 * Implementations:
 * - [AnthropicProviderInput]
 * - [AzureOpenAIProviderInput]
 * - [BaseProviderInput]
 * - [ManagedProviderResponseInput]
 * - [OpenAICompatibleProviderInput]
 * - [OpenAIProviderInput]
 * - [XAIProviderInput]
 */
@Serializable(InputUnionSerializer::class)
public sealed interface InputUnion {
  @Serializable
  @JvmInline
  public value class AzureOpenAIProviderInputValue(public val value: AzureOpenAIProviderInput) :
    InputUnion

  @Serializable
  @JvmInline
  public value class OpenAICompatibleProviderInputValue(
    public val value: OpenAICompatibleProviderInput
  ) : InputUnion

  @Serializable
  @JvmInline
  public value class OpenAIProviderInputValue(public val value: OpenAIProviderInput) : InputUnion

  @Serializable
  @JvmInline
  public value class BaseProviderInputValue(public val value: BaseProviderInput) : InputUnion

  @Serializable
  @JvmInline
  public value class AnthropicProviderInputValue(public val value: AnthropicProviderInput) :
    InputUnion

  @Serializable
  @JvmInline
  public value class XAIProviderInputValue(public val value: XAIProviderInput) : InputUnion

  @Serializable
  @JvmInline
  public value class ManagedProviderResponseInputValue(
    public val value: ManagedProviderResponseInput
  ) : InputUnion

  public companion object {

    public fun of(value: AzureOpenAIProviderInput): InputUnion =
      AzureOpenAIProviderInputValue(value)

    public fun of(value: OpenAICompatibleProviderInput): InputUnion =
      OpenAICompatibleProviderInputValue(value)

    public fun of(value: OpenAIProviderInput): InputUnion = OpenAIProviderInputValue(value)

    public fun of(value: BaseProviderInput): InputUnion = BaseProviderInputValue(value)

    public fun of(value: AnthropicProviderInput): InputUnion = AnthropicProviderInputValue(value)

    public fun of(value: XAIProviderInput): InputUnion = XAIProviderInputValue(value)

    public fun of(value: ManagedProviderResponseInput): InputUnion =
      ManagedProviderResponseInputValue(value)
  }
}

internal class InputUnionSerializer :
  JsonContentPolymorphicSerializer<InputUnion>(InputUnion::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<InputUnion> {
    return when {
      element is JsonObject &&
        element.containsKey("azureDeployment") &&
        element.containsKey("azureEndpoint") -> AzureOpenAIProviderInput.serializer()
      element is JsonObject &&
        element.containsKey("baseUrl") &&
        element.containsKey("defaultModel") -> OpenAICompatibleProviderInput.serializer()
      element is JsonObject -> OpenAIProviderInput.serializer()
      element is JsonObject -> BaseProviderInput.serializer()
      element is JsonObject -> AnthropicProviderInput.serializer()
      element is JsonObject -> XAIProviderInput.serializer()
      element is JsonObject -> ManagedProviderResponseInput.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
