/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * InsidePolygonUnion
 *
 * Implementations:
 * - [List<List<Double>>] - *[InsidePolygonUnion.of]*
 * - [String] - *[InsidePolygonUnion.of]*
 */
@Serializable(InsidePolygonUnionSerializer::class)
public sealed interface InsidePolygonUnion {
  @Serializable
  @JvmInline
  public value class StringValue(public val value: String) : InsidePolygonUnion

  @Serializable
  @JvmInline
  public value class ListOfListOfDoubleValue(public val value: List<List<Double>>) :
    InsidePolygonUnion

  public companion object {

    public fun of(value: String): InsidePolygonUnion = StringValue(value)

    public fun of(value: List<List<Double>>): InsidePolygonUnion = ListOfListOfDoubleValue(value)
  }
}

internal class InsidePolygonUnionSerializer :
  JsonContentPolymorphicSerializer<InsidePolygonUnion>(InsidePolygonUnion::class) {
  override fun selectDeserializer(
    element: JsonElement
  ): DeserializationStrategy<InsidePolygonUnion> {
    return when {
      element.isString -> InsidePolygonUnion.StringValue.serializer()
      element is JsonArray -> InsidePolygonUnion.ListOfListOfDoubleValue.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
