/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * McpServerToolConfig
 *
 * @param url
 * @param headers
 * @param name
 * @param type
 * @param transport
 * @param id Stable unique identifier for this MCP tool.
 * @param allowedTools
 */
@Serializable
public data class McpServerToolConfig(
  @SerialName(value = "url") val url: String,
  @SerialName(value = "headers") val headers: Map<kotlin.String, String>,
  @SerialName(value = "name") val name: String,
  @SerialName(value = "type") val type: String,
  @SerialName(value = "transport") val transport: String? = null,

  /** Stable unique identifier for this MCP tool. */
  @SerialName(value = "id") val id: String? = null,
  @SerialName(value = "allowedTools") val allowedTools: JsonObject? = null,
) : ToolConfigInput {}
