/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/** The type of the stored memory. */
@Serializable
public enum class MemoryType(public val value: kotlin.String) {

  @SerialName(value = "semantic") Semantic("semantic"),
  @SerialName(value = "episodic") Episodic("episodic");

  override fun toString(): kotlin.String = value
}
