/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * MessagesUnion
 *
 * Implementations:
 * - [List<MessageV4>] - *[MessagesUnion.ofListOfMessageV4]*
 * - [List<MessageV5>] - *[MessagesUnion.ofListOfMessageV5]*
 */
@Serializable(MessagesUnionSerializer::class)
public sealed interface MessagesUnion {
  @Serializable
  @JvmInline
  public value class ListOfMessageV4Value(public val value: List<MessageV4>) : MessagesUnion

  @Serializable
  @JvmInline
  public value class ListOfMessageV5Value(public val value: List<MessageV5>) : MessagesUnion

  public companion object {
    public fun ofListOfMessageV4(value: List<MessageV4>): MessagesUnion {
      return ListOfMessageV4Value(value)
    }

    public fun ofListOfMessageV5(value: List<MessageV5>): MessagesUnion {
      return ListOfMessageV5Value(value)
    }
  }
}

internal class MessagesUnionSerializer :
  JsonContentPolymorphicSerializer<MessagesUnion>(MessagesUnion::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<MessagesUnion> {
    return when {
      element is JsonArray -> MessagesUnion.ListOfMessageV4Value.serializer()
      element is JsonArray -> MessagesUnion.ListOfMessageV5Value.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
