/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Response model for a message.
 *
 * @param id
 * @param conversationId
 * @param role
 * @param parts
 * @param createdAt
 * @param updatedAt
 * @param model
 * @param inputTokens
 * @param outputTokens
 * @param turnContext
 */
@Serializable
public data class MessageResponse(
  @SerialName(value = "id") val id: String,
  @SerialName(value = "conversationId") val conversationId: String,
  @SerialName(value = "role") val role: MessageRole,
  @SerialName(value = "parts") val parts: List<MessagePart>,
  @SerialName(value = "createdAt") val createdAt: String,
  @SerialName(value = "updatedAt") val updatedAt: String,
  @SerialName(value = "model") val model: String? = null,
  @SerialName(value = "inputTokens") val inputTokens: Int? = null,
  @SerialName(value = "outputTokens") val outputTokens: Int? = null,
  @SerialName(value = "turnContext") val turnContext: Map<kotlin.String, String>? = null,
) {}
