/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * NumericFiltersUnion
 *
 * Implementations:
 * - [List<NumericFiltersUnion>] - *[NumericFiltersUnion.of]*
 * - [String] - *[NumericFiltersUnion.of]*
 */
@Serializable(NumericFiltersUnionSerializer::class)
public sealed interface NumericFiltersUnion {
  @Serializable
  @JvmInline
  public value class StringValue(public val value: String) : NumericFiltersUnion

  @Serializable
  @JvmInline
  public value class ListOfNumericFiltersUnionValue(public val value: List<NumericFiltersUnion>) :
    NumericFiltersUnion

  public companion object {

    public fun of(value: String): NumericFiltersUnion = StringValue(value)

    public fun of(value: List<NumericFiltersUnion>): NumericFiltersUnion =
      ListOfNumericFiltersUnionValue(value)
  }
}

internal class NumericFiltersUnionSerializer :
  JsonContentPolymorphicSerializer<NumericFiltersUnion>(NumericFiltersUnion::class) {
  override fun selectDeserializer(
    element: JsonElement
  ): DeserializationStrategy<NumericFiltersUnion> {
    return when {
      element.isString -> NumericFiltersUnion.StringValue.serializer()
      element is JsonArray -> NumericFiltersUnion.ListOfNumericFiltersUnionValue.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
