/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * OpenAI-compatible provider input. Contrary to the OpenAIProviderInput, the base_url is required.
 * A model is required to verify connectivity and get saved as the default model. This can later be
 * changed at the Agent level.
 *
 * @param apiKey
 * @param baseUrl
 * @param defaultModel Default model for this provider. Used for validation and as fallback when no
 *   model is specified at agent level.
 */
@Serializable
public data class OpenAICompatibleProviderInput(
  @SerialName(value = "apiKey") val apiKey: String,
  @SerialName(value = "baseUrl") val baseUrl: String,

  /**
   * Default model for this provider. Used for validation and as fallback when no model is specified
   * at agent level.
   */
  @SerialName(value = "defaultModel") val defaultModel: String,
) : ProviderInputNullable, ProviderInput {}
