/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * PaginatedConversationsResponse
 *
 * @param `data`
 * @param pagination
 */
@Serializable
public data class PaginatedConversationsResponse(
  @SerialName(value = "data") val `data`: List<ConversationBaseResponse>,
  @SerialName(value = "pagination") val pagination: PaginationMetadata,
) {}
