/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * ProviderInputNullable
 *
 * Implementations:
 * - [AnthropicProviderInput]
 * - [AzureOpenAIProviderInput]
 * - [BaseProviderInput]
 * - [OpenAICompatibleProviderInput]
 * - [OpenAIProviderInput]
 */
@Serializable(ProviderInputNullableSerializer::class)
public sealed interface ProviderInputNullable {
  @Serializable
  @JvmInline
  public value class AzureOpenAIProviderInputValue(public val value: AzureOpenAIProviderInput) :
    ProviderInputNullable

  @Serializable
  @JvmInline
  public value class OpenAICompatibleProviderInputValue(
    public val value: OpenAICompatibleProviderInput
  ) : ProviderInputNullable

  @Serializable
  @JvmInline
  public value class OpenAIProviderInputValue(public val value: OpenAIProviderInput) :
    ProviderInputNullable

  @Serializable
  @JvmInline
  public value class BaseProviderInputValue(public val value: BaseProviderInput) :
    ProviderInputNullable

  @Serializable
  @JvmInline
  public value class AnthropicProviderInputValue(public val value: AnthropicProviderInput) :
    ProviderInputNullable

  public companion object {

    public fun of(value: AzureOpenAIProviderInput): ProviderInputNullable =
      AzureOpenAIProviderInputValue(value)

    public fun of(value: OpenAICompatibleProviderInput): ProviderInputNullable =
      OpenAICompatibleProviderInputValue(value)

    public fun of(value: OpenAIProviderInput): ProviderInputNullable =
      OpenAIProviderInputValue(value)

    public fun of(value: BaseProviderInput): ProviderInputNullable = BaseProviderInputValue(value)

    public fun of(value: AnthropicProviderInput): ProviderInputNullable =
      AnthropicProviderInputValue(value)
  }
}

internal class ProviderInputNullableSerializer :
  JsonContentPolymorphicSerializer<ProviderInputNullable>(ProviderInputNullable::class) {
  override fun selectDeserializer(
    element: JsonElement
  ): DeserializationStrategy<ProviderInputNullable> {
    return when {
      element is JsonObject &&
        element.containsKey("azureDeployment") &&
        element.containsKey("azureEndpoint") -> AzureOpenAIProviderInput.serializer()
      element is JsonObject &&
        element.containsKey("baseUrl") &&
        element.containsKey("defaultModel") -> OpenAICompatibleProviderInput.serializer()
      element is JsonObject -> OpenAIProviderInput.serializer()
      element is JsonObject -> BaseProviderInput.serializer()
      element is JsonObject -> AnthropicProviderInput.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
