/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ReasoningPartV4
 *
 * @param reasoning
 * @param type
 */
@Serializable
public data class ReasoningPartV4(
  @SerialName(value = "reasoning") val reasoning: String,
  @SerialName(value = "type") val type: String? = null,
) : AssistantPartV4 {}
