/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * ReRankingApplyFilterUnion
 *
 * Implementations:
 * - [List<JsonObject>] - *[ReRankingApplyFilterUnion.of]*
 * - [String] - *[ReRankingApplyFilterUnion.of]*
 */
@Serializable(ReRankingApplyFilterUnionSerializer::class)
public sealed interface ReRankingApplyFilterUnion {
  @Serializable
  @JvmInline
  public value class StringValue(public val value: String) : ReRankingApplyFilterUnion

  @Serializable
  @JvmInline
  public value class ListOfJsonObjectValue(public val value: List<JsonObject>) :
    ReRankingApplyFilterUnion

  public companion object {

    public fun of(value: String): ReRankingApplyFilterUnion = StringValue(value)

    public fun of(value: List<JsonObject>): ReRankingApplyFilterUnion = ListOfJsonObjectValue(value)
  }
}

internal class ReRankingApplyFilterUnionSerializer :
  JsonContentPolymorphicSerializer<ReRankingApplyFilterUnion>(ReRankingApplyFilterUnion::class) {
  override fun selectDeserializer(
    element: JsonElement
  ): DeserializationStrategy<ReRankingApplyFilterUnion> {
    return when {
      element.isString -> ReRankingApplyFilterUnion.StringValue.serializer()
      element is JsonArray -> ReRankingApplyFilterUnion.ListOfJsonObjectValue.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
