/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Secret key creation payload.
 *
 * @param name The name of the secret key.
 * @param agentIds List of agent IDs this secret key is associated with.
 */
@Serializable
public data class SecretKeyCreate(

  /** The name of the secret key. */
  @SerialName(value = "name") val name: String,

  /** List of agent IDs this secret key is associated with. */
  @SerialName(value = "agentIds") val agentIds: List<String>? = null,
) {}
