/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Response body for a completed task run.
 *
 * @param output
 */
@Serializable
public data class TaskResponse(@SerialName(value = "output") val output: JsonObject) {}
