/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * ToolConfigInput
 *
 * Implementations:
 * - [AlgoliaDisplayResultsToolConfig]
 * - [AlgoliaRecommendToolConfigInput]
 * - [AlgoliaSearchToolConfig]
 * - [ClientSideToolConfig]
 * - [McpServerToolConfig]
 * - [UnknownToolConfig]
 */
@Serializable(ToolConfigInputSerializer::class)
public sealed interface ToolConfigInput {
  @Serializable
  @JvmInline
  public value class ClientSideToolConfigValue(public val value: ClientSideToolConfig) :
    ToolConfigInput

  @Serializable
  @JvmInline
  public value class McpServerToolConfigValue(public val value: McpServerToolConfig) :
    ToolConfigInput

  @Serializable
  @JvmInline
  public value class AlgoliaSearchToolConfigValue(public val value: AlgoliaSearchToolConfig) :
    ToolConfigInput

  @Serializable
  @JvmInline
  public value class AlgoliaRecommendToolConfigInputValue(
    public val value: AlgoliaRecommendToolConfigInput
  ) : ToolConfigInput

  @Serializable
  @JvmInline
  public value class AlgoliaDisplayResultsToolConfigValue(
    public val value: AlgoliaDisplayResultsToolConfig
  ) : ToolConfigInput

  @Serializable
  @JvmInline
  public value class UnknownToolConfigValue(public val value: UnknownToolConfig) : ToolConfigInput

  public companion object {

    public fun of(value: ClientSideToolConfig): ToolConfigInput = ClientSideToolConfigValue(value)

    public fun of(value: McpServerToolConfig): ToolConfigInput = McpServerToolConfigValue(value)

    public fun of(value: AlgoliaSearchToolConfig): ToolConfigInput =
      AlgoliaSearchToolConfigValue(value)

    public fun of(value: AlgoliaRecommendToolConfigInput): ToolConfigInput =
      AlgoliaRecommendToolConfigInputValue(value)

    public fun of(value: AlgoliaDisplayResultsToolConfig): ToolConfigInput =
      AlgoliaDisplayResultsToolConfigValue(value)

    public fun of(value: UnknownToolConfig): ToolConfigInput = UnknownToolConfigValue(value)
  }
}

internal class ToolConfigInputSerializer :
  JsonContentPolymorphicSerializer<ToolConfigInput>(ToolConfigInput::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<ToolConfigInput> {
    when (element.jsonObject["type"]?.jsonPrimitive?.contentOrNull) {
      "algolia_display_results" -> return AlgoliaDisplayResultsToolConfig.serializer()
      "algolia_recommend" -> return AlgoliaRecommendToolConfigInput.serializer()
      "algolia_search_index" -> return AlgoliaSearchToolConfig.serializer()
      "client_side" -> return ClientSideToolConfig.serializer()
      "mcp_tools" -> return McpServerToolConfig.serializer()
      "unknown" -> return UnknownToolConfig.serializer()
    }
    return when {
      element is JsonObject &&
        element.containsKey("description") &&
        element.containsKey("inputSchema") -> ClientSideToolConfig.serializer()
      element is JsonObject && element.containsKey("headers") && element.containsKey("url") ->
        McpServerToolConfig.serializer()
      element is JsonObject && element.containsKey("indices") ->
        AlgoliaSearchToolConfig.serializer()
      element is JsonObject -> AlgoliaRecommendToolConfigInput.serializer()
      element is JsonObject -> AlgoliaDisplayResultsToolConfig.serializer()
      element is JsonObject -> UnknownToolConfig.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
