/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ToolInvocationPartV4
 *
 * @param toolInvocation
 * @param type
 */
@Serializable
public data class ToolInvocationPartV4(
  @SerialName(value = "toolInvocation") val toolInvocation: ToolInvocationV4,
  @SerialName(value = "type") val type: String? = null,
) : AssistantPartV4 {}
