/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * ToolConfig
 *
 * Implementations:
 * - [Boolean] - *[ToolConfig.of]*
 * - [McpToolConfig]
 */
@Serializable(ToolConfigSerializer::class)
public sealed interface ToolConfig {
  @Serializable
  @JvmInline
  public value class McpToolConfigValue(public val value: McpToolConfig) : ToolConfig

  @Serializable @JvmInline public value class BooleanValue(public val value: Boolean) : ToolConfig

  public companion object {

    public fun of(value: McpToolConfig): ToolConfig = McpToolConfigValue(value)

    public fun of(value: Boolean): ToolConfig = BooleanValue(value)
  }
}

internal class ToolConfigSerializer :
  JsonContentPolymorphicSerializer<ToolConfig>(ToolConfig::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<ToolConfig> {
    return when {
      element is JsonObject -> McpToolConfig.serializer()
      element.isBoolean -> ToolConfig.BooleanValue.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
