/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

@Serializable
public enum class ToolState(public val value: kotlin.String) {

  @SerialName(value = "input-streaming") InputStreaming("input-streaming"),
  @SerialName(value = "input-available") InputAvailable("input-available"),
  @SerialName(value = "output-available") OutputAvailable("output-available"),
  @SerialName(value = "output-error") OutputError("output-error");

  override fun toString(): kotlin.String = value
}
