/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Model for tool invocation in a Message.
 *
 * @param toolCallId
 * @param toolName
 * @param args
 * @param result
 * @param step
 * @param state
 * @param providerOptions
 * @param requiresApproval
 * @param description
 * @param argsHash
 */
@Serializable
public data class ToolInvocationV4(
  @SerialName(value = "toolCallId") val toolCallId: String,
  @SerialName(value = "toolName") val toolName: String,
  @SerialName(value = "args") val args: JsonObject? = null,
  @SerialName(value = "result") val result: JsonObject? = null,
  @SerialName(value = "step") val step: Int? = null,
  @SerialName(value = "state") val state: String? = null,
  @SerialName(value = "providerOptions") val providerOptions: JsonObject? = null,
  @SerialName(value = "requiresApproval") val requiresApproval: Boolean? = null,
  @SerialName(value = "description") val description: String? = null,
  @SerialName(value = "argsHash") val argsHash: String? = null,
) {}
