/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ToolCallPart
 *
 * @param type
 * @param toolCallId
 * @param toolName
 * @param args
 * @param requiresApproval
 * @param providerOptions
 */
@Serializable
public data class ToolCallPart(
  @SerialName(value = "type") val type: String,
  @SerialName(value = "toolCallId") val toolCallId: String,
  @SerialName(value = "toolName") val toolName: String,
  @SerialName(value = "args") val args: JsonElement? = null,
  @SerialName(value = "requiresApproval") val requiresApproval: Boolean? = null,
  @SerialName(value = "providerOptions") val providerOptions: JsonObject? = null,
) : MessagePart {}
