/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * ToolConfigOrBooleanUnion
 *
 * Implementations:
 * - [Boolean] - *[ToolConfigOrBooleanUnion.of]*
 * - [McpToolConfig]
 */
@Serializable(ToolConfigOrBooleanUnionSerializer::class)
public sealed interface ToolConfigOrBooleanUnion {
  @Serializable
  @JvmInline
  public value class McpToolConfigValue(public val value: McpToolConfig) : ToolConfigOrBooleanUnion

  @Serializable
  @JvmInline
  public value class BooleanValue(public val value: Boolean) : ToolConfigOrBooleanUnion

  public companion object {

    public fun of(value: McpToolConfig): ToolConfigOrBooleanUnion = McpToolConfigValue(value)

    public fun of(value: Boolean): ToolConfigOrBooleanUnion = BooleanValue(value)
  }
}

internal class ToolConfigOrBooleanUnionSerializer :
  JsonContentPolymorphicSerializer<ToolConfigOrBooleanUnion>(ToolConfigOrBooleanUnion::class) {
  override fun selectDeserializer(
    element: JsonElement
  ): DeserializationStrategy<ToolConfigOrBooleanUnion> {
    return when {
      element is JsonObject -> McpToolConfig.serializer()
      element.isBoolean -> ToolConfigOrBooleanUnion.BooleanValue.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
