/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Model for tool invocation in a Message.
 *
 * @param type
 * @param toolCallId
 * @param state
 * @param input
 * @param output
 * @param errorText
 * @param providerOptions
 * @param requiresApproval
 * @param description
 * @param argsHash
 */
@Serializable
public data class ToolPartV5(
  @SerialName(value = "type") val type: String,
  @SerialName(value = "toolCallId") val toolCallId: String,
  @SerialName(value = "state") val state: ToolState? = null,
  @SerialName(value = "input") val input: JsonObject? = null,
  @SerialName(value = "output") val output: JsonObject? = null,
  @SerialName(value = "errorText") val errorText: String? = null,
  @SerialName(value = "providerOptions") val providerOptions: JsonObject? = null,
  @SerialName(value = "requiresApproval") val requiresApproval: Boolean? = null,
  @SerialName(value = "description") val description: String? = null,
  @SerialName(value = "argsHash") val argsHash: String? = null,
) : AssistantPartV5 {}
