/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.agentstudio

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ValidationError
 *
 * @param loc
 * @param msg
 * @param type
 * @param input
 * @param ctx
 */
@Serializable
public data class ValidationError(
  @SerialName(value = "loc") val loc: List<LocationItemUnion>,
  @SerialName(value = "msg") val msg: String,
  @SerialName(value = "type") val type: String,
  @SerialName(value = "input") val input: JsonElement? = null,
  @SerialName(value = "ctx") val ctx: JsonObject? = null,
) {}
