/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Update to perform on the attribute.
 *
 * @param operation
 * @param `value`
 */
@Serializable
public data class BuiltInOperation(
  @SerialName(value = "_operation") val operation: BuiltInOperationType,
  @SerialName(value = "value") val `value`: BuiltInOperationValue,
) : AttributeToUpdate {}
