/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Redirect to a virtual replica index. This consequence is only valid for rules with `scope:
 * redirect`.
 *
 * @param indexName Name of the virtual replica index to redirect searches to.
 */
@Serializable
public data class ConsequenceRedirect(

  /** Name of the virtual replica index to redirect searches to. */
  @SerialName(value = "indexName") val indexName: String
) {}
