/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.search

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*
import kotlin.jvm.JvmInline

/**
 * MixedSearchFilters
 *
 * Implementations:
 * - [List<String>] - *[MixedSearchFilters.of]*
 * - [String] - *[MixedSearchFilters.of]*
 */
@Serializable(MixedSearchFiltersSerializer::class)
public sealed interface MixedSearchFilters {
  @Serializable
  @JvmInline
  public value class ListOfStringValue(public val value: List<String>) : MixedSearchFilters

  @Serializable
  @JvmInline
  public value class StringValue(public val value: String) : MixedSearchFilters

  public companion object {

    public fun of(value: List<String>): MixedSearchFilters {
      return ListOfStringValue(value)
    }
    public fun of(value: String): MixedSearchFilters {
      return StringValue(value)
    }
  }
}

internal class MixedSearchFiltersSerializer : JsonContentPolymorphicSerializer<MixedSearchFilters>(MixedSearchFilters::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<MixedSearchFilters> {
    return when {
      element.isJsonArrayOfPrimitives -> MixedSearchFilters.ListOfStringValue.serializer()
      element.isString -> MixedSearchFilters.StringValue.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
