/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.search

import kotlinx.serialization.*

/** Classification of the query scope. */
@Serializable
public enum class QueryCategorizationType(public val value: kotlin.String) {

  @SerialName(value = "narrow") Narrow("narrow"),
  @SerialName(value = "broad") Broad("broad"),
  @SerialName(value = "ambiguous") Ambiguous("ambiguous"),
  @SerialName(value = "none") None("none");

  override fun toString(): kotlin.String = value
}
