/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ReplaceAllObjectsResponse
 *
 * @param copyOperationResponse
 * @param batchResponses The response of the `batch` request(s).
 * @param moveOperationResponse
 */
@Serializable
public data class ReplaceAllObjectsResponse(
  @SerialName(value = "copyOperationResponse") val copyOperationResponse: UpdatedAtResponse,

  /** The response of the `batch` request(s). */
  @SerialName(value = "batchResponses") val batchResponses: List<BatchResponse>,
  @SerialName(value = "moveOperationResponse") val moveOperationResponse: UpdatedAtResponse,
) {}
