/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * SearchDictionaryEntriesResponse
 *
 * @param hits Dictionary entries matching the search criteria.
 * @param page Requested page of the API response.
 * @param nbHits Number of results (hits).
 * @param nbPages Number of pages of results.
 */
@Serializable
public data class SearchDictionaryEntriesResponse(

  /** Dictionary entries matching the search criteria. */
  @SerialName(value = "hits") val hits: List<DictionaryEntry>,

  /** Requested page of the API response. */
  @SerialName(value = "page") val page: Int,

  /** Number of results (hits). */
  @SerialName(value = "nbHits") val nbHits: Int,

  /** Number of pages of results. */
  @SerialName(value = "nbPages") val nbPages: Int,
)
