/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TimeRange
 *
 * @param from When the rule should start to be active, in Unix epoch time.
 * @param until When the rule should stop to be active, in Unix epoch time.
 */
@Serializable
public data class TimeRange(

  /** When the rule should start to be active, in Unix epoch time. */
  @SerialName(value = "from") val from: Int,

  /** When the rule should stop to be active, in Unix epoch time. */
  @SerialName(value = "until") val until: Int,
)
