package serialize

import client.serialize.*
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.JUnit4
import kotlin.test.assertEquals


@RunWith(JUnit4::class)
class TestKeys {

    @Test
    fun keys() {
        assertEquals(KeyQuery, "query")
        assertEquals(KeySearchableAttributes, "searchableAttributes")
        assertEquals(KeyAttributesForFaceting, "attributesForFaceting")
        assertEquals(KeyUnretrievableAttributes, "UnretrievableAttributes")
        assertEquals(KeyAttributesToRetrieve, "attributesToRetrieve")
        assertEquals(KeyRestrictSearchableAttributes, "restrictSearchableAttributes")
        assertEquals(KeyRanking, "ranking")
        assertEquals(KeyCustomRanking, "customRanking")
        assertEquals(KeyReplicas, "replicas")
        assertEquals(KeyFilters, "filters")
        assertEquals(KeyFacetFilters, "facetFilters")
        assertEquals(KeyOptionalFilters, "optionalFilters")
        assertEquals(KeyNumericFilters, "numericFilters")
        assertEquals(KeyTagFilters, "tagFilters")
        assertEquals(KeySumOrFiltersScores, "sumOrFiltersScores")
        assertEquals(KeyFacets, "facets")
        assertEquals(KeyMaxValuesPerFacet, "maxValuesPerFacet")
        assertEquals(KeyFacetingAfterDistinct, "facetingAfterDistinct")
        assertEquals(KeySortFacetValuesBy, "sortFacetValuesBy")
        assertEquals(KeyAttributesToHighlight, "attributesToHighlight")
        assertEquals(KeyAttributesToSnippet, "attributesToSnippet")
        assertEquals(KeyHighlightPreTag, "highlightPreTag")
        assertEquals(KeyHighlightPostTag, "highlightPostTag")
        assertEquals(KeySnippetEllipsisText, "snippetEllipsisText")
        assertEquals(KeyRestrictHighlightAndSnippetArrays, "restrictHighlightAndSnippetArrays")
        assertEquals(KeyPage, "page")
        assertEquals(KeyHitsPerPage, "hitsPerPage")
        assertEquals(KeyOffset, "offset")
        assertEquals(KeyLength, "length")
        assertEquals(KeyPaginationLimitedTo, "paginationLimitedTo")
        assertEquals(KeyMinWordSizefor1Typo, "minWordSizefor1Typo")
        assertEquals(KeyMinWordSizefor2Typos, "minWordSizefor2Typos")
        assertEquals(KeyTypoTolerance, "typoTolerance")
        assertEquals(KeyAllowTyposOnNumericTokens, "allowTyposOnNumericTokens")
        assertEquals(KeyDisableTypoToleranceOnAttributes, "disableTypoToleranceOnAttributes")
        assertEquals(KeyDisableTypoToleranceOnWords, "disableTypoToleranceOnWords")
        assertEquals(KeySeparatorsToIndex, "separatorsToIndex")
        assertEquals(KeyAroundLatLng, "aroundLatLng")
        assertEquals(KeyAroundLatLngViaIP, "aroundLatLngViaIP")
        assertEquals(KeyAroundRadius, "aroundRadius")
        assertEquals(KeyAroundPrecision, "aroundPrecision")
        assertEquals(KeyMinimumAroundRadius, "minimumAroundRadius")
        assertEquals(KeyInsideBoundingBox, "insideBoundingBox")
        assertEquals(KeyInsidePolygon, "insidePolygon")
        assertEquals(KeyIgnorePlurals, "ignorePlurals")
        assertEquals(KeyRemoveStopWords, "removeStopWords")
        assertEquals(KeyCamelCaseAttributes, "camelCaseAttributes")
        assertEquals(KeyDecompoundedAttributes, "decompoundedAttributes")
        assertEquals(KeyKeepDiacriticsOnCharacters, "keepDiacriticsOnCharacters")
        assertEquals(KeyQueryLanguages, "queryLanguages")
        assertEquals(KeyEnableRules, "enableRules")
        assertEquals(KeyRuleContexts, "ruleContexts")
        assertEquals(KeyEnablePersonalization, "enablePersonalization")
        assertEquals(KeyQueryType, "queryType")
        assertEquals(KeyRemoveWordsIfNoResults, "removeWordsIfNoResults")
        assertEquals(KeyAdvancedSyntax, "advancedSyntax")
        assertEquals(KeyOptionalWords, "optionalWords")
        assertEquals(KeyDisablePrefixOnAttributes, "disablePrefixOnAttributes")
        assertEquals(KeyDisableExactOnAttributes, "disableExactOnAttributes")
        assertEquals(KeyExactOnSingleWordQuery, "exactOnSingleWordQuery")
        assertEquals(KeyAlternativesAsExact, "alternativesAsExact")
        assertEquals(KeyNumericAttributesForFiltering, "numericAttributesForFiltering")
        assertEquals(KeyAllowCompressionOfIntegerArray, "allowCompressionOfIntegerArray")
        assertEquals(KeyAttributeForDistinct, "attributeForDistinct")
        assertEquals(KeyDistinct, "distinct")
        assertEquals(KeyGetRankingInfo, "getRankingInfo")
        assertEquals(KeyClickAnalytics, "clickAnalytics")
        assertEquals(KeyAnalytics, "analytics")
        assertEquals(KeyAnalyticsTags, "analyticsTags")
        assertEquals(KeySynonyms, "synonyms")
        assertEquals(KeyReplaceSynonymsInHighlight, "replaceSynonymsInHighlight")
        assertEquals(KeyMinProximity, "minProximity")
        assertEquals(KeyResponseFields, "responseFields")
        assertEquals(KeyMaxFacetHits, "maxFacetHits")
        assertEquals(KeyPercentileComputation, "percentileComputation")
        assertEquals(KeyGeo, "geo")
        assertEquals(KeyTypo, "typo")
        assertEquals(KeyWords, "words")
        assertEquals(KeyProximity, "proximity")
        assertEquals(KeyAttribute, "attribute")
        assertEquals(KeyExact, "exact")
        assertEquals(KeyCustom, "custom")
        assertEquals(KeyAsc, "asc")
        assertEquals(KeyDesc, "desc")
        assertEquals(KeyStrict, "strict")
        assertEquals(KeyMin, "min")
    }
}