/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.api

import com.algolia.client.configuration.*
import com.algolia.client.exception.*
import com.algolia.client.extensions.internal.*
import com.algolia.client.model.agentstudio.*
import com.algolia.client.transport.*
import com.algolia.client.transport.internal.*
import kotlin.time.Duration.Companion.milliseconds
import kotlinx.serialization.json.*

/**
 * Beta: The Agent Studio API is not yet stable and may change without notice.
 *
 * @see [Agent Studio API docs](https://www.algolia.com/doc/rest-api/agent-studio)
 */
public class AgentStudioClient(
  override val appId: String,
  override var apiKey: String,
  override val options: ClientOptions = ClientOptions(),
) : ApiClient {

  init {
    require(appId.isNotBlank()) { "`appId` is missing." }
    require(apiKey.isNotBlank()) { "`apiKey` is missing." }
  }

  override val requester: Requester =
    requesterOf(
      clientName = "AgentStudio",
      appId = appId,
      apiKey = apiKey,
      connectTimeout = 25000.milliseconds,
      readTimeout = 25000.milliseconds,
      writeTimeout = 25000.milliseconds,
      options = options,
    ) {
      listOf(
        Host("$appId-dsn.algolia.net", CallType.Read),
        Host("$appId.algolia.net", CallType.Write),
      ) +
        mutableListOf(
            Host("$appId-1.algolianet.com"),
            Host("$appId-2.algolianet.com"),
            Host("$appId-3.algolianet.com"),
          )
          .apply { shuffle() }
    }

  /**
   * Add multiple allowed domain patterns. Duplicates are skipped.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param agentId The agentId.
   * @param allowedDomainBulkInsert
   * @param requestOptions additional request configuration.
   */
  public suspend fun bulkCreateAllowedDomains(
    agentId: String,
    allowedDomainBulkInsert: AllowedDomainBulkInsert,
    requestOptions: RequestOptions? = null,
  ): AllowedDomainListResponse {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `bulkCreateAllowedDomains`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "allowed-domains", "bulk"),
        body = allowedDomainBulkInsert,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Delete allowed domains by id list.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param agentId The agentId.
   * @param allowedDomainBulkDelete
   * @param requestOptions additional request configuration.
   */
  public suspend fun bulkDeleteAllowedDomains(
    agentId: String,
    allowedDomainBulkDelete: AllowedDomainBulkDelete,
    requestOptions: RequestOptions? = null,
  ) {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `bulkDeleteAllowedDomains`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "allowed-domains", "bulk"),
        body = allowedDomainBulkDelete,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Create a new agent.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param agentConfigCreate
   * @param requestOptions additional request configuration.
   */
  public suspend fun createAgent(
    agentConfigCreate: AgentConfigCreate,
    requestOptions: RequestOptions? = null,
  ): AgentWithVersionResponse {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path = "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "agents"),
        body = agentConfigCreate,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Add a single allowed domain pattern (e.g. https://app.example.com or *.example.com).
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param agentId The agentId.
   * @param allowedDomainCreate
   * @param requestOptions additional request configuration.
   */
  public suspend fun createAgentAllowedDomain(
    agentId: String,
    allowedDomainCreate: AllowedDomainCreate,
    requestOptions: RequestOptions? = null,
  ): AllowedDomainResponse {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `createAgentAllowedDomain`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "allowed-domains"),
        body = allowedDomainCreate,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Create a completion for the specified agent. This endpoint handles two types of requests: 1.
   * Normal completion request: User message -> Agent response 2. Tool approval response: User
   * approval -> Execute tool -> Agent response Tool Approval Flow (for MCP tools with
   * requiresApproval: true): - Request 1: User sends message -> Agent requests tool call -> Return
   * approval request - Request 2: User approves -> Execute tool -> Agent continues with result.
   *
   * Required API Key ACLs:
   * - search
   *
   * @param agentId The agentId.
   * @param compatibilityMode Compatibility mode for the completion API.
   * @param agentCompletionRequest
   * @param stream Whether to stream the response or not. (default to true)
   * @param cache Use cached responses if available. (default to true)
   * @param memory Set to false to disable memory (enabled by default).
   * @param analytics Set to false to skip analytics for this completion (default: true). Disables
   *   Agent Studio BigQuery analytics, Algolia search analytics, click analytics, and
   *   query-suggestions training. Useful for offline-eval workflows. (default to true)
   * @param xAlgoliaSecureUserToken The X-Algolia-Secure-User-Token.
   * @param requestOptions additional request configuration.
   */
  public suspend fun createAgentCompletion(
    agentId: String,
    compatibilityMode: CompatibilityMode,
    agentCompletionRequest: AgentCompletionRequest,
    stream: Boolean? = null,
    cache: Boolean? = null,
    memory: Boolean? = null,
    analytics: Boolean? = null,
    xAlgoliaSecureUserToken: String? = null,
    requestOptions: RequestOptions? = null,
  ): Map<kotlin.String, Any> {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `createAgentCompletion`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "completions"),
        headers =
          buildMap {
            xAlgoliaSecureUserToken?.let { header -> put("X-Algolia-Secure-User-Token", header) }
          },
        query =
          buildMap {
            put("compatibilityMode", compatibilityMode)
            stream?.let { put("stream", it) }
            cache?.let { put("cache", it) }
            memory?.let { put("memory", it) }
            analytics?.let { put("analytics", it) }
          },
        body = agentCompletionRequest,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Create new feedback entry.
   *
   * Required API Key ACLs:
   * - search
   *
   * @param feedbackCreationRequest
   * @param requestOptions additional request configuration.
   */
  public suspend fun createFeedback(
    feedbackCreationRequest: FeedbackCreationRequest,
    requestOptions: RequestOptions? = null,
  ): FeedbackResponse {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path = "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "feedback"),
        body = feedbackCreationRequest,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Create Provider.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param providerAuthenticationCreate
   * @param requestOptions additional request configuration.
   */
  public suspend fun createProvider(
    providerAuthenticationCreate: ProviderAuthenticationCreate,
    requestOptions: RequestOptions? = null,
  ): ProviderAuthenticationResponse {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path = "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "providers"),
        body = providerAuthenticationCreate,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Create Secret Key.
   *
   * Required API Key ACLs:
   * - admin
   *
   * @param secretKeyCreate
   * @param requestOptions additional request configuration.
   */
  public suspend fun createSecretKey(
    secretKeyCreate: SecretKeyCreate,
    requestOptions: RequestOptions? = null,
  ): SecretKeyResponse {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path = "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "secret-keys"),
        body = secretKeyCreate,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`.
   * @param parameters Query parameters to apply to the current query.
   * @param requestOptions additional request configuration.
   */
  public suspend fun customDelete(
    path: String,
    parameters: Map<kotlin.String, Any>? = null,
    requestOptions: RequestOptions? = null,
  ): JsonObject {
    require(path.isNotBlank()) { "Parameter `path` is required when calling `customDelete`." }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path = "/agent-studio/{path}".replace("{path}", path),
        query = buildMap { parameters?.let { putAll(it) } },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`.
   * @param parameters Query parameters to apply to the current query.
   * @param requestOptions additional request configuration.
   */
  public suspend fun customGet(
    path: String,
    parameters: Map<kotlin.String, Any>? = null,
    requestOptions: RequestOptions? = null,
  ): JsonObject {
    require(path.isNotBlank()) { "Parameter `path` is required when calling `customGet`." }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path = "/agent-studio/{path}".replace("{path}", path),
        query = buildMap { parameters?.let { putAll(it) } },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`.
   * @param parameters Query parameters to apply to the current query.
   * @param body Parameters to send with the custom request.
   * @param requestOptions additional request configuration.
   */
  public suspend fun customPost(
    path: String,
    parameters: Map<kotlin.String, Any>? = null,
    body: JsonObject? = null,
    requestOptions: RequestOptions? = null,
  ): JsonObject {
    require(path.isNotBlank()) { "Parameter `path` is required when calling `customPost`." }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path = "/agent-studio/{path}".replace("{path}", path),
        query = buildMap { parameters?.let { putAll(it) } },
        body = body,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`.
   * @param parameters Query parameters to apply to the current query.
   * @param body Parameters to send with the custom request.
   * @param requestOptions additional request configuration.
   */
  public suspend fun customPut(
    path: String,
    parameters: Map<kotlin.String, Any>? = null,
    body: JsonObject? = null,
    requestOptions: RequestOptions? = null,
  ): JsonObject {
    require(path.isNotBlank()) { "Parameter `path` is required when calling `customPut`." }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.PUT,
        path = "/agent-studio/{path}".replace("{path}", path),
        query = buildMap { parameters?.let { putAll(it) } },
        body = body,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Delete the specified agent.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param agentId The agentId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun deleteAgent(agentId: String, requestOptions: RequestOptions? = null) {
    require(agentId.isNotBlank()) { "Parameter `agentId` is required when calling `deleteAgent`." }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "agents", "$agentId"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Deletes the conversations matching the given filers.
   *
   * Required API Key ACLs:
   * - logs
   *
   * @param agentId The agentId.
   * @param startDate Filter conversations created after this date (format: YYYY-MM-DD).
   * @param endDate Filter conversations created before this date (format: YYYY-MM-DD).
   * @param requestOptions additional request configuration.
   */
  public suspend fun deleteAgentConversations(
    agentId: String,
    startDate: String? = null,
    endDate: String? = null,
    requestOptions: RequestOptions? = null,
  ) {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `deleteAgentConversations`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "conversations"),
        query =
          buildMap {
            startDate?.let { put("startDate", it) }
            endDate?.let { put("endDate", it) }
          },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Remove an allowed domain by id.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param domainId The domainId.
   * @param agentId The agentId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun deleteAllowedDomain(
    domainId: String,
    agentId: String,
    requestOptions: RequestOptions? = null,
  ) {
    require(domainId.isNotBlank()) {
      "Parameter `domainId` is required when calling `deleteAllowedDomain`."
    }
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `deleteAllowedDomain`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "allowed-domains", "$domainId"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Deletes the conversation with the given ID.
   *
   * Required API Key ACLs:
   * - logs
   *
   * @param conversationId The conversationId.
   * @param agentId The agentId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun deleteConversation(
    conversationId: String,
    agentId: String,
    requestOptions: RequestOptions? = null,
  ) {
    require(conversationId.isNotBlank()) {
      "Parameter `conversationId` is required when calling `deleteConversation`."
    }
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `deleteConversation`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "conversations", "$conversationId"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Delete Provider.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param providerId The providerId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun deleteProvider(providerId: String, requestOptions: RequestOptions? = null) {
    require(providerId.isNotBlank()) {
      "Parameter `providerId` is required when calling `deleteProvider`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "providers", "$providerId"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Delete Secret Key.
   *
   * Required API Key ACLs:
   * - admin
   *
   * @param secretKeyId The secretKeyId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun deleteSecretKey(secretKeyId: String, requestOptions: RequestOptions? = null) {
    require(secretKeyId.isNotBlank()) {
      "Parameter `secretKeyId` is required when calling `deleteSecretKey`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "secret-keys", "$secretKeyId"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Permanently deletes all messages for the given user token. Does not delete conversations.
   *
   * Required API Key ACLs:
   * - logs
   *
   * @param userToken The userToken.
   * @param requestOptions additional request configuration.
   */
  public suspend fun deleteUserData(userToken: String, requestOptions: RequestOptions? = null) {
    require(userToken.isNotBlank()) {
      "Parameter `userToken` is required when calling `deleteUserData`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "user-data", "$userToken"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Exports all conversations based on the passed filters.
   *
   * Required API Key ACLs:
   * - logs
   *
   * @param agentId The agentId.
   * @param startDate Filter conversations created after this date (format: YYYY-MM-DD).
   * @param endDate Filter conversations created before this date (format: YYYY-MM-DD).
   * @param requestOptions additional request configuration.
   */
  public suspend fun exportConversations(
    agentId: String,
    startDate: String? = null,
    endDate: String? = null,
    requestOptions: RequestOptions? = null,
  ): List<ConversationFullResponse> {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `exportConversations`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "conversations", "export"),
        query =
          buildMap {
            startDate?.let { put("startDate", it) }
            endDate?.let { put("endDate", it) }
          },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Retrieve details of the specified agent.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param agentId The agentId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun getAgent(
    agentId: String,
    requestOptions: RequestOptions? = null,
  ): AgentWithVersionResponse {
    require(agentId.isNotBlank()) { "Parameter `agentId` is required when calling `getAgent`." }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "agents", "$agentId"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Get a single allowed domain by id.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param domainId The domainId.
   * @param agentId The agentId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun getAllowedDomain(
    domainId: String,
    agentId: String,
    requestOptions: RequestOptions? = null,
  ): AllowedDomainResponse {
    require(domainId.isNotBlank()) {
      "Parameter `domainId` is required when calling `getAllowedDomain`."
    }
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `getAllowedDomain`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "allowed-domains", "$domainId"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Get Configuration.
   *
   * Required API Key ACLs:
   * - logs
   *
   * @param requestOptions additional request configuration.
   */
  public suspend fun getConfiguration(
    requestOptions: RequestOptions? = null
  ): ApplicationConfigResponse {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path = "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "configuration"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Retrieves the conversation and its messages for the given ID.
   *
   * Required API Key ACLs:
   * - logs
   *
   * @param conversationId The conversationId.
   * @param agentId The agentId.
   * @param includeFeedback Include feedback for the conversation. (default to false)
   * @param xAlgoliaSecureUserToken The X-Algolia-Secure-User-Token.
   * @param requestOptions additional request configuration.
   */
  public suspend fun getConversation(
    conversationId: String,
    agentId: String,
    includeFeedback: Boolean? = null,
    xAlgoliaSecureUserToken: String? = null,
    requestOptions: RequestOptions? = null,
  ): ConversationFullResponse {
    require(conversationId.isNotBlank()) {
      "Parameter `conversationId` is required when calling `getConversation`."
    }
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `getConversation`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "conversations", "$conversationId"),
        headers =
          buildMap {
            xAlgoliaSecureUserToken?.let { header -> put("X-Algolia-Secure-User-Token", header) }
          },
        query = buildMap { includeFeedback?.let { put("includeFeedback", it) } },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Get Provider.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param providerId The providerId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun getProvider(
    providerId: String,
    requestOptions: RequestOptions? = null,
  ): ProviderAuthenticationResponse {
    require(providerId.isNotBlank()) {
      "Parameter `providerId` is required when calling `getProvider`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "providers", "$providerId"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Get Secret Key.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param secretKeyId The secretKeyId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun getSecretKey(
    secretKeyId: String,
    requestOptions: RequestOptions? = null,
  ): SecretKeyResponse {
    require(secretKeyId.isNotBlank()) {
      "Parameter `secretKeyId` is required when calling `getSecretKey`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "secret-keys", "$secretKeyId"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Retrieves all memories, conversations and their messages for the given user token.
   *
   * Required API Key ACLs:
   * - logs
   *
   * @param userToken The userToken.
   * @param requestOptions additional request configuration.
   */
  public suspend fun getUserData(
    userToken: String,
    requestOptions: RequestOptions? = null,
  ): UserDataResponse {
    require(userToken.isNotBlank()) {
      "Parameter `userToken` is required when calling `getUserData`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "user-data", "$userToken"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Invalidate cached completions for this agent. Filter with `before` (exclusive).
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param agentId The agentId.
   * @param before Delete entries strictly before this date (exclusive, YYYY-MM-DD).
   * @param requestOptions additional request configuration.
   */
  public suspend fun invalidateAgentCache(
    agentId: String,
    before: String? = null,
    requestOptions: RequestOptions? = null,
  ) {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `invalidateAgentCache`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.DELETE,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "cache"),
        query = buildMap { before?.let { put("before", it) } },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * List all allowed domain patterns for this agent.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param agentId The agentId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun listAgentAllowedDomains(
    agentId: String,
    requestOptions: RequestOptions? = null,
  ): AllowedDomainListResponse {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `listAgentAllowedDomains`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "allowed-domains"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Retrieves the conversations for the given agent ID.
   *
   * Required API Key ACLs:
   * - logs
   *
   * @param agentId The agentId.
   * @param startDate Filter conversations created after this date (format: YYYY-MM-DD).
   * @param endDate Filter conversations created before this date (format: YYYY-MM-DD).
   * @param includeFeedback Include feedback per conversation.
   * @param feedbackVote Filter by feedback value (requires includeFeedback=true).
   * @param page Page number. (default to 1)
   * @param limit Items per page. (default to 20)
   * @param xAlgoliaSecureUserToken The X-Algolia-Secure-User-Token.
   * @param requestOptions additional request configuration.
   */
  public suspend fun listAgentConversations(
    agentId: String,
    startDate: String? = null,
    endDate: String? = null,
    includeFeedback: Boolean? = null,
    feedbackVote: Int? = null,
    page: Int? = null,
    limit: Int? = null,
    xAlgoliaSecureUserToken: String? = null,
    requestOptions: RequestOptions? = null,
  ): PaginatedConversationsResponse {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `listAgentConversations`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "conversations"),
        headers =
          buildMap {
            xAlgoliaSecureUserToken?.let { header -> put("X-Algolia-Secure-User-Token", header) }
          },
        query =
          buildMap {
            startDate?.let { put("startDate", it) }
            endDate?.let { put("endDate", it) }
            includeFeedback?.let { put("includeFeedback", it) }
            feedbackVote?.let { put("feedbackVote", it) }
            page?.let { put("page", it) }
            limit?.let { put("limit", it) }
          },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * List all agents with pagination and filtering.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param page Page number. (default to 1)
   * @param limit Items per page. (default to 10)
   * @param providerId Filter by provider id.
   * @param requestOptions additional request configuration.
   */
  public suspend fun listAgents(
    page: Int? = null,
    limit: Int? = null,
    providerId: String? = null,
    requestOptions: RequestOptions? = null,
  ): PaginatedAgentsResponse {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path = "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "agents"),
        query =
          buildMap {
            page?.let { put("page", it) }
            limit?.let { put("limit", it) }
            providerId?.let { put("providerId", it) }
          },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Get Provider Models.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param requestOptions additional request configuration.
   */
  public suspend fun listModels(
    requestOptions: RequestOptions? = null
  ): Map<kotlin.String, List<String>> {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "providers", "models"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Get available models for a specific provider.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param providerId The providerId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun listProviderModels(
    providerId: String,
    requestOptions: RequestOptions? = null,
  ): List<String> {
    require(providerId.isNotBlank()) {
      "Parameter `providerId` is required when calling `listProviderModels`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "providers", "$providerId", "models"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * List Providers.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param page Page number. (default to 1)
   * @param limit Items per page. (default to 10)
   * @param requestOptions additional request configuration.
   */
  public suspend fun listProviders(
    page: Int? = null,
    limit: Int? = null,
    requestOptions: RequestOptions? = null,
  ): PaginatedProviderAuthenticationsResponse {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path = "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "providers"),
        query =
          buildMap {
            page?.let { put("page", it) }
            limit?.let { put("limit", it) }
          },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * List Secret Keys.
   *
   * Required API Key ACLs:
   * - settings
   *
   * @param page Page number. (default to 1)
   * @param limit Items per page. (default to 10)
   * @param requestOptions additional request configuration.
   */
  public suspend fun listSecretKeys(
    page: Int? = null,
    limit: Int? = null,
    requestOptions: RequestOptions? = null,
  ): PaginatedSecretKeysResponse {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.GET,
        path = "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "secret-keys"),
        query =
          buildMap {
            page?.let { put("page", it) }
            limit?.let { put("limit", it) }
          },
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Publish the specified agent.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param agentId The agentId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun publishAgent(
    agentId: String,
    requestOptions: RequestOptions? = null,
  ): AgentWithVersionResponse {
    require(agentId.isNotBlank()) { "Parameter `agentId` is required when calling `publishAgent`." }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "publish"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Unpublish the specified agent.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param agentId The agentId.
   * @param requestOptions additional request configuration.
   */
  public suspend fun unpublishAgent(
    agentId: String,
    requestOptions: RequestOptions? = null,
  ): AgentWithVersionResponse {
    require(agentId.isNotBlank()) {
      "Parameter `agentId` is required when calling `unpublishAgent`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.POST,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "agents", "$agentId", "unpublish"),
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Update the specified agent.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param agentId The agentId.
   * @param agentConfigUpdate
   * @param requestOptions additional request configuration.
   */
  public suspend fun updateAgent(
    agentId: String,
    agentConfigUpdate: AgentConfigUpdate,
    requestOptions: RequestOptions? = null,
  ): AgentWithVersionResponse {
    require(agentId.isNotBlank()) { "Parameter `agentId` is required when calling `updateAgent`." }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.PATCH,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "agents", "$agentId"),
        body = agentConfigUpdate,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Patch Configuration.
   *
   * Required API Key ACLs:
   * - logs
   *
   * @param applicationConfigPatch
   * @param requestOptions additional request configuration.
   */
  public suspend fun updateConfiguration(
    applicationConfigPatch: ApplicationConfigPatch,
    requestOptions: RequestOptions? = null,
  ): ApplicationConfigResponse {
    val requestConfig =
      RequestConfig(
        method = RequestMethod.PATCH,
        path = "/agent-studio".split("/").filter { it.isNotBlank() } + listOf("1", "configuration"),
        body = applicationConfigPatch,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Update Provider.
   *
   * Required API Key ACLs:
   * - editSettings
   *
   * @param providerId The providerId.
   * @param providerAuthenticationPatch
   * @param requestOptions additional request configuration.
   */
  public suspend fun updateProvider(
    providerId: String,
    providerAuthenticationPatch: ProviderAuthenticationPatch,
    requestOptions: RequestOptions? = null,
  ): ProviderAuthenticationResponse {
    require(providerId.isNotBlank()) {
      "Parameter `providerId` is required when calling `updateProvider`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.PATCH,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "providers", "$providerId"),
        body = providerAuthenticationPatch,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Patch Secret Key.
   *
   * Required API Key ACLs:
   * - admin
   *
   * @param secretKeyId The secretKeyId.
   * @param secretKeyPatch
   * @param requestOptions additional request configuration.
   */
  public suspend fun updateSecretKey(
    secretKeyId: String,
    secretKeyPatch: SecretKeyPatch,
    requestOptions: RequestOptions? = null,
  ): SecretKeyResponse {
    require(secretKeyId.isNotBlank()) {
      "Parameter `secretKeyId` is required when calling `updateSecretKey`."
    }
    val requestConfig =
      RequestConfig(
        method = RequestMethod.PATCH,
        path =
          "/agent-studio".split("/").filter { it.isNotBlank() } +
            listOf("1", "secret-keys", "$secretKeyId"),
        body = secretKeyPatch,
      )
    return requester.execute(requestConfig = requestConfig, requestOptions = requestOptions)
  }

  /**
   * Helper: Forges a secured user token (JWT) for Agent Studio authenticated requests.
   *
   * @param secretKey The secret key to sign the token with.
   * @param secretKeyId The key ID to include in the JWT header (kid).
   * @param userId The user identifier to include as the subject (sub) claim.
   * @param expiresIn The token expiration in seconds from now. Defaults to 86400 (24 hours).
   * @return The signed JWT token.
   */
  public fun forgeSecuredUserToken(
    secretKey: String,
    secretKeyId: String,
    userId: String,
    expiresIn: Int = 24 * 3600,
  ): String {
    fun base64UrlEncode(data: ByteArray): String =
      kotlin.io.encoding.Base64.UrlSafe.encode(data).trimEnd('=')

    fun hmacSHA256(key: String, message: String): ByteArray {
      val hex = com.algolia.client.extensions.internal.encodeKeySHA256(key, message)
      return hex.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
    }

    val now = kotlinx.datetime.Clock.System.now().epochSeconds
    val header =
      base64UrlEncode("""{"alg":"HS256","typ":"JWT","kid":"$secretKeyId"}""".encodeToByteArray())
    val payload =
      base64UrlEncode("""{"sub":"$userId","exp":${now + expiresIn}}""".encodeToByteArray())
    val signature = base64UrlEncode(hmacSHA256(secretKey, "$header.$payload"))

    return "$header.$payload.$signature"
  }
}
