/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.monitoring

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * LatencyMetric
 *
 * @param latency
 */
@Serializable
public data class LatencyMetric(

  @SerialName(value = "latency") val latency: Map<kotlin.String, List<TimeEntry>>? = null,
)
