/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*

/**
 * Which indexing operation to perform: - `addObject`: adds records to an index. Equivalent to the
 * \"Add a new record (with auto-generated object ID)\" operation. - `updateObject`: adds or
 * replaces records in an index. Equivalent to the \"Add or replace a record\" operation. -
 * `partialUpdateObject`: adds or updates attributes within records. Equivalent to the \"Add or
 * update attributes\" operation with the `createIfNoExists` parameter set to true. (If a record
 * with the specified `objectID` doesn't exist in the specified index, this action creates adds the
 * record to the index) - `partialUpdateObjectNoCreate`: same as `partialUpdateObject`, but with
 * `createIfNoExists` set to false. (A record isn't added to the index if its `objectID` doesn't
 * exist) - `deleteObject`: delete records from an index. Equivalent to the \"Delete a record\"
 * operation. - `delete`. Delete an index. Equivalent to the \"Delete an index\" operation. -
 * `clear`: delete all records from an index. Equivalent to the \"Delete all records from an index
 * operation\".
 */
@Serializable
public enum class Action(public val value: kotlin.String) {

  @SerialName(value = "addObject") AddObject("addObject"),
  @SerialName(value = "updateObject") UpdateObject("updateObject"),
  @SerialName(value = "partialUpdateObject") PartialUpdateObject("partialUpdateObject"),
  @SerialName(value = "partialUpdateObjectNoCreate")
  PartialUpdateObjectNoCreate("partialUpdateObjectNoCreate"),
  @SerialName(value = "deleteObject") DeleteObject("deleteObject"),
  @SerialName(value = "delete") Delete("delete"),
  @SerialName(value = "clear") Clear("clear");

  override fun toString(): kotlin.String = value
}
