/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*

/**
 * Type of indexing operation.
 */
@Serializable
public enum class Action(public val value: kotlin.String) {

  @SerialName(value = "addObject")
  AddObject("addObject"),

  @SerialName(value = "updateObject")
  UpdateObject("updateObject"),

  @SerialName(value = "partialUpdateObject")
  PartialUpdateObject("partialUpdateObject"),

  @SerialName(value = "partialUpdateObjectNoCreate")
  PartialUpdateObjectNoCreate("partialUpdateObjectNoCreate");

  override fun toString(): kotlin.String = value
}
