/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * AuthInput
 *
 * Implementations:
 * - [AuthAPIKey]
 * - [AuthAlgolia]
 * - [AuthBasic]
 * - [AuthGoogleServiceAccount]
 * - [AuthOAuth]
 */
@Serializable(AuthInputSerializer::class)
public sealed interface AuthInput {

  public companion object {
  }
}

internal class AuthInputSerializer : JsonContentPolymorphicSerializer<AuthInput>(AuthInput::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<AuthInput> {
    return when {
      element is JsonObject -> AuthGoogleServiceAccount.serializer()
      element is JsonObject -> AuthBasic.serializer()
      element is JsonObject -> AuthAPIKey.serializer()
      element is JsonObject -> AuthOAuth.serializer()
      element is JsonObject -> AuthAlgolia.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
