/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Credentials for authenticating with an API key.
 *
 * @param key API key. This field is `null` in the API response.
 */
@Serializable
public data class AuthAPIKey(

  /** API key. This field is `null` in the API response. */
  @SerialName(value = "key") val key: String
) : AuthInput {}
