/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Credentials for authenticating with user name and password.
 *
 * @param username Username.
 * @param password Password. This field is `null` in the API response.
 */
@Serializable
public data class AuthBasic(

  /** Username. */
  @SerialName(value = "username") val username: String,

  /** Password. This field is `null` in the API response. */
  @SerialName(value = "password") val password: String,
) : AuthInput {}
