/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Request body for updating an authentication resource.
 *
 * @param type
 * @param name Descriptive name for the resource.
 * @param input
 */
@Serializable
public data class AuthenticationUpdate(
  @SerialName(value = "type") val type: AuthenticationType? = null,

  /** Descriptive name for the resource. */
  @SerialName(value = "name") val name: String? = null,
  @SerialName(value = "input") val input: AuthInputPartial? = null,
) {}
