/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * BigCommerceChannel
 *
 * @param id ID of the BigCommerce channel.
 * @param currencies Currencies for the given channel.
 */
@Serializable
public data class BigCommerceChannel(

  /** ID of the BigCommerce channel. */
  @SerialName(value = "id") val id: Int,

  /** Currencies for the given channel. */
  @SerialName(value = "currencies") val currencies: List<String>? = null,
)
