/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * DeleteResponse
 *
 * @param deletedAt Date and time when the resource was deleted, in RFC 3339 format.
 */
@Serializable
public data class DeleteResponse(

  /** Date and time when the resource was deleted, in RFC 3339 format. */
  @SerialName(value = "deletedAt") val deletedAt: String
) {}
