/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * API request body for searching destinations.
 *
 * @param destinationIDs
 */
@Serializable
public data class DestinationSearch(

  @SerialName(value = "destinationIDs") val destinationIDs: List<String>,
)
