/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*

/** The strategy to use to fetch the data. */
@Serializable
public enum class DockerStreamsSyncMode(public val value: kotlin.String) {

  @SerialName(value = "incremental") Incremental("incremental"),
  @SerialName(value = "fullTable") FullTable("fullTable");

  override fun toString(): kotlin.String = value
}
