/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Transformations to apply to source, serialized as a JSON string.
 *
 * @param format Name of the mapping format schema, `mappingkit/v1` is currently the only supported format.
 * @param actions
 */
@Serializable
public data class MappingInput(

  /** Name of the mapping format schema, `mappingkit/v1` is currently the only supported format. */
  @SerialName(value = "format") val format: String,

  @SerialName(value = "actions") val actions: List<MappingKitAction>,
)
