/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*

/**
 * Record type for ecommerce sources.
 */
@Serializable
public enum class RecordType(public val value: kotlin.String) {

  @SerialName(value = "product")
  Product("product"),

  @SerialName(value = "variant")
  Variant("variant"),

  @SerialName(value = "collection")
  Collection("collection");

  override fun toString(): kotlin.String = value
}
