/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Run
 *
 * @param runID Universally unique identifier (UUID) of a task run.
 * @param appID
 * @param taskID Universally unique identifier (UUID) of a task.
 * @param status
 * @param type
 * @param createdAt Date of creation in RFC3339 format.
 * @param progress
 * @param outcome
 * @param failureThreshold Maximum accepted percentage of failures for a task run to finish successfully.
 * @param reason More information about the task run's outcome.
 * @param reasonCode
 * @param startedAt Date of start in RFC3339 format.
 * @param finishedAt Date of finish in RFC3339 format.
 */
@Serializable
public data class Run(

  /** Universally unique identifier (UUID) of a task run. */
  @SerialName(value = "runID") val runID: String,

  @SerialName(value = "appID") val appID: String,

  /** Universally unique identifier (UUID) of a task. */
  @SerialName(value = "taskID") val taskID: String,

  @SerialName(value = "status") val status: RunStatus,

  @SerialName(value = "type") val type: RunType,

  /** Date of creation in RFC3339 format. */
  @SerialName(value = "createdAt") val createdAt: String,

  @SerialName(value = "progress") val progress: RunProgress? = null,

  @SerialName(value = "outcome") val outcome: RunOutcome? = null,

  /** Maximum accepted percentage of failures for a task run to finish successfully. */
  @SerialName(value = "failureThreshold") val failureThreshold: Int? = null,

  /** More information about the task run's outcome. */
  @SerialName(value = "reason") val reason: String? = null,

  @SerialName(value = "reasonCode") val reasonCode: RunReasonCode? = null,

  /** Date of start in RFC3339 format. */
  @SerialName(value = "startedAt") val startedAt: String? = null,

  /** Date of finish in RFC3339 format. */
  @SerialName(value = "finishedAt") val finishedAt: String? = null,
)
