/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * RunSourceResponse
 *
 * @param taskWithRunID Map of taskID sent for reindex with the corresponding runID.
 * @param createdAt Date and time when the resource was created, in RFC 3339 format.
 */
@Serializable
public data class RunSourceResponse(

  /** Map of taskID sent for reindex with the corresponding runID. */
  @SerialName(value = "taskWithRunID") val taskWithRunID: Map<kotlin.String, String>,

  /** Date and time when the resource was created, in RFC 3339 format. */
  @SerialName(value = "createdAt") val createdAt: String,
) {}
