/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Trigger information for scheduled tasks.
 *
 * @param type
 * @param cron Cron expression for the task's schedule.
 * @param nextRun The next scheduled run of the task in RFC 3339 format.
 * @param lastRun The last time the scheduled task ran in RFC 3339 format.
 */
@Serializable
public data class ScheduleTrigger(

  @SerialName(value = "type") val type: ScheduleTriggerType,

  /** Cron expression for the task's schedule. */
  @SerialName(value = "cron") val cron: String,

  /** The next scheduled run of the task in RFC 3339 format. */
  @SerialName(value = "nextRun") val nextRun: String,

  /** The last time the scheduled task ran in RFC 3339 format. */
  @SerialName(value = "lastRun") val lastRun: String? = null,
) : Trigger
