/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Source
 *
 * @param sourceID Universally uniqud identifier (UUID) of a source.
 * @param type
 * @param name
 * @param input
 * @param createdAt Date of creation in RFC3339 format.
 * @param authenticationID Universally unique identifier (UUID) of an authentication resource.
 * @param updatedAt Date of last update in RFC3339 format.
 */
@Serializable
public data class Source(

  /** Universally uniqud identifier (UUID) of a source. */
  @SerialName(value = "sourceID") val sourceID: String,

  @SerialName(value = "type") val type: SourceType,

  @SerialName(value = "name") val name: String,

  @SerialName(value = "input") val input: SourceInput,

  /** Date of creation in RFC3339 format. */
  @SerialName(value = "createdAt") val createdAt: String,

  /** Universally unique identifier (UUID) of an authentication resource. */
  @SerialName(value = "authenticationID") val authenticationID: String? = null,

  /** Date of last update in RFC3339 format. */
  @SerialName(value = "updatedAt") val updatedAt: String? = null,
)
