/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * SourceCreate
 *
 * @param type
 * @param name Descriptive name of the source.
 * @param input
 * @param authenticationID Universally unique identifier (UUID) of an authentication resource.
 */
@Serializable
public data class SourceCreate(

  @SerialName(value = "type") val type: SourceType,

  /** Descriptive name of the source. */
  @SerialName(value = "name") val name: String,

  @SerialName(value = "input") val input: SourceInput,

  /** Universally unique identifier (UUID) of an authentication resource. */
  @SerialName(value = "authenticationID") val authenticationID: String? = null,
)
