/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Input for a `streaming` task whose source is of type `ga4BigqueryExport` and for which extracted
 * data is continuously streamed.
 *
 * @param mapping
 */
@Serializable
public data class StreamingInput(@SerialName(value = "mapping") val mapping: MappingInput) :
  TaskInput {}
