/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*

/** The type of transformation, which can be either 'code' or 'noCode'. */
@Serializable
public enum class TransformationType(public val value: kotlin.String) {

  @SerialName(value = "code") Code("code"),
  @SerialName(value = "noCode") NoCode("noCode");

  override fun toString(): kotlin.String = value
}
