/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TransformationTry
 *
 * @param sampleRecord The record to apply the given code to.
 * @param code It is deprecated. Use the `input` field with proper `type` instead to specify the
 *   transformation code.
 * @param type
 * @param input
 * @param authentications
 */
@Serializable
public data class TransformationTry(

  /** The record to apply the given code to. */
  @SerialName(value = "sampleRecord") val sampleRecord: JsonObject,

  /**
   * It is deprecated. Use the `input` field with proper `type` instead to specify the
   * transformation code.
   */
  @Deprecated(message = "This property is deprecated.")
  @SerialName(value = "code")
  val code: String? = null,
  @SerialName(value = "type") val type: TransformationType? = null,
  @SerialName(value = "input") val input: TransformationInput? = null,
  @SerialName(value = "authentications") val authentications: List<AuthenticationCreate>? = null,
) {}
