package client.response

import client.Index
import client.data.*
import client.data.Attribute
import client.data.NumericAttributes
import client.data.Ranking
import client.data.WordDecompounding
import kotlinx.serialization.Serializable


@Serializable
data class Settings(
    val searchableAttributes: List<Attribute>? = null,
    val attributesForFaceting: List<Attribute>? = null,
    val unretrievableAttributes: List<Attribute>? = null,
    val attributesToRetrieve: List<Attribute>? = null,
    val ranking: Ranking? = null,
    val customRanking: CustomRanking? = null,
    val replicas: List<Index>? = null,
    val filters: String? = null,
    val facetFilters: List<List<String>>? = null,
    val optionalFilters: List<List<String>>? = null,
    val numericFilters: List<List<String>>? = null,
    val tagFilters: List<List<String>>? = null,
    val sumOrFilterScores: Boolean? = null,
    val facets: List<Attribute>? = null,
    val maxValuesPerFacet: Int? = null,
    val facetingAfterDistinct: Boolean? = null,
    val sortFacetValuesBy: SortFacetValuesBy? = null,
    val attributesToHighlight: List<Attribute>? = null,
    val attributesToSnippet: List<String>? = null,
    val highlightPreTag: String? = null,
    val highlightPostTag: String? = null,
    val snippetEllipsisText: String? = null,
    val restrictHighlightAndSnippetArrays: Boolean? = null,
    val page: Int? = null,
    val hitsPerPage: Int? = null,
    val offer: Int? = null,
    val length: Int? = null,
    val paginationLimitedTo: Int? = null,
    val minWordSizefor1Typo: Int? = null,
    val minWordSizefor2Typos: Int? = null,
    val typoTolerance: TypoTolerance? = null,
    val allowTyposOnNumericTokens: Boolean? = null,
    val disableTypoToleranceOnAttributes: List<Attribute>? = null,
    val disableTypoToleranceOnWords: List<String>? = null,
    val separatorsToIndex: String? = null,
    val aroundLatLng: String? = null,
    val aroundLatLngViaIP: Boolean? = null,
    val aroundRadius: AroundRadius? = null,
    val aroundPrecision: Int? = null,
    val minimumAroundRadius: Int? = null,
    val insideBoundingBox: List<Float>? = null,
    val insidePolygon: List<Float>? = null,
    val ignorePlurals: BooleanOrQueryLanguages? = null,
    val removeStopWords: BooleanOrQueryLanguages? = null,
    val camelCaseAttributes: List<Attribute>? = null,
    val decompoundedAttributes: WordDecompounding? = null,
    val keepDiacriticsOnCharacters: String? = null,
    val queryLanguages: List<QueryLanguage>? = null,
    val enableRules: Boolean? = null,
    val ruleContexts: List<String>? = null,
    val queryType: QueryType? = null,
    val removeWordsIfNoResults: RemoveWordIfNoResults? = null,
    val advancedSyntax: Boolean? = null,
    val optionalWords: List<String>? = null,
    val disablePrefixOnAttributes: List<Attribute>? = null,
    val disableExactOnAttributes: List<Attribute>? = null,
    val exactOnSingleWordQuery: ExactOnSingleWordQuery? = null,
    val alternativesAsExact: AlternativesAsExact? = null,
    val numericAttributesForFiltering: List<NumericAttributes>? = null,
    val allowCompressionOfIntegerArray: Boolean? = null,
    val attributeForDistinct: Attribute? = null,
    val distinct: Int? = null,
    val getRankingInfo: Boolean? = null,
    val clickAnalytics: Boolean? = null,
    val analytics: Boolean? = null,
    val analyticsTags: List<String>? = null,
    val synonyms: Boolean? = null,
    val replaceSynonymsInHighlight: Boolean? = null,
    val minProximity: Int? = null,
    val responseFields: List<ResponseFields>? = null,
    val maxFacetHits: Int? = null,
    val percentileComputation: Boolean? = null
)