package com.algolia.search.saas.model

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable


@Serializable
data class Params(
    @Optional val automaticFacetFilters: List<AutomaticFacetFilters>? = null,
    @Optional val automaticOptionalFacetFilters: List<AutomaticFacetFilters>? = null,
    @Optional val query: QueryOrEdits? = null,
    @Optional val attributesToRetrieve: List<Attribute>? = null,
    @Optional val restrictSearchableAttributes: List<Attribute>? = null,
    @Optional val filters: String? = null,
    @Optional val facetFilters: List<List<String>>? = null,
    @Optional val optionalFilters: List<List<String>>? = null,
    @Optional val numericFilters: List<List<String>>? = null,
    @Optional val tagFilters: List<List<String>>? = null,
    @Optional val sumOrFiltersScores: Boolean? = null,
    @Optional val facets: List<Attribute>? = null,
    @Optional val maxValuesPerFacet: Int? = null,
    @Optional val facetingAfterDistinct: Boolean? = null,
    @Optional val sortFacetValuesBy: SortFacetValuesBy? = null,
    @Optional val attributesToHighlight: List<Attribute>? = null,
    @Optional val attributesToSnippet: List<Snippet>? = null,
    @Optional val highlightPreTag: String? = null,
    @Optional val highlightPostTag: String? = null,
    @Optional val snippetEllipsisText: String? = null,
    @Optional val restrictHighlightAndSnippetArrays: Boolean? = null,
    @Optional val page: Int? = null,
    @Optional val hitsPerPage: Int? = null,
    @Optional val offset: Int? = null,
    @Optional val length: Int? = null,
    @Optional val minWordSizefor1Typo: Int? = null,
    @Optional val minWordSizefor2Typos: Int? = null,
    @Optional val typoTolerance: TypoTolerance? = null,
    @Optional val allowTyposOnNumericTokens: Boolean? = null,
    @Optional val disableTypoToleranceOnAttributes: List<Attribute>? = null,
    @Optional val aroundLatLng: String? = null,
    @Optional val aroundLatLngViaIP: Boolean? = null,
    @Optional val aroundRadius: AroundRadius? = null,
    @Optional val aroundPrecision: Int? = null,
    @Optional val minimumAroundRadius: Int? = null,
    @Optional val insideBoundingBox: List<BoundingBox>? = null,
    @Optional val insidePolygon: List<Polygon>? = null,
    @Optional val ignorePlurals: BooleanOrQueryLanguages? = null,
    @Optional val removeStopWords: BooleanOrQueryLanguages? = null,
    @Optional val queryLanguages: List<QueryLanguage>? = null,
    @Optional val enableRules: Boolean? = null,
    @Optional val ruleContexts: List<String>? = null,
    @Optional val enablePersonalization: Boolean? = null,
    @Optional val queryType: QueryType? = null,
    @Optional val removeWordsIfNoResults: RemoveWordIfNoResults? = null,
    @Optional val advancedSyntax: Boolean? = null,
    @Optional val optionalWords: List<String>? = null,
    @Optional val disableExactOnAttributes: List<Attribute>? = null,
    @Optional val exactOnSingleWordQuery: ExactOnSingleWordQuery? = null,
    @Optional val alternativesAsExact: List<AlternativesAsExact>? = null,
    @Optional val distinct: Int? = null,
    @Optional val getRankingInfo: Boolean? = null,
    @Optional val clickAnalytics: Boolean? = null,
    @Optional val analytics: Boolean? = null,
    @Optional val analyticsTags: List<String>? = null,
    @Optional val synonyms: Boolean? = null,
    @Optional val replaceSynonymsInHighlight: Boolean? = null,
    @Optional val minProximity: Int? = null,
    @Optional val responseFields: List<ResponseFields>? = null,
    @Optional val maxFacetHits: Int? = null,
    @Optional val percentileComputation: Boolean? = null
)