/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * url for a search banner image.
 *
 * @param url
 */
@Serializable
public data class BannerImageUrl(

  @SerialName(value = "url") val url: String? = null,
)
