/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Order of facet names and facet values in your UI.
 *
 * @param facets
 * @param values Order of facet values. One object for each facet.
 */
@Serializable
public data class FacetOrdering(

  @SerialName(value = "facets") val facets: IndexSettingsFacets? = null,

  /** Order of facet values. One object for each facet. */
  @SerialName(value = "values") val values: Map<kotlin.String, Value>? = null,
)
