/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Records to promote.
 *
 * @param objectIDs Object IDs of the records you want to promote.  The records are placed as a group at the `position`. For example, if you want to promote four records to position `0`, they will be the first four search results.
 * @param position Position in the search results where you want to show the promoted records.
 */
@Serializable
public data class PromoteObjectIDs(

  /** Object IDs of the records you want to promote.  The records are placed as a group at the `position`. For example, if you want to promote four records to position `0`, they will be the first four search results.  */
  @SerialName(value = "objectIDs") val objectIDs: List<String>,

  /** Position in the search results where you want to show the promoted records. */
  @SerialName(value = "position") val position: Int,
) : Promote
