/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * RecommendationsHits
 *
 * @param hits
 * @param query Search query.
 * @param params URL-encoded string of all search parameters.
 */
@Serializable
public data class RecommendationsHits(

  @SerialName(value = "hits") val hits: List<RecommendationsHit>,

  /** Search query. */
  @SerialName(value = "query") val query: String? = null,

  /** URL-encoded string of all search parameters. */
  @SerialName(value = "params") val params: String? = null,
)
