/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Trending facet hit.
 *
 * @param facetName Facet attribute. To be used in combination with `facetValue`. If specified, only recommendations matching the facet filter will be returned.
 * @param facetValue Facet value. To be used in combination with `facetName`. If specified, only recommendations matching the facet filter will be returned.
 * @param score Recommendation score.
 */
@Serializable
public data class TrendingFacetHit(

  /** Facet attribute. To be used in combination with `facetValue`. If specified, only recommendations matching the facet filter will be returned.  */
  @SerialName(value = "facetName") val facetName: String,

  /** Facet value. To be used in combination with `facetName`. If specified, only recommendations matching the facet filter will be returned.  */
  @SerialName(value = "facetValue") val facetValue: String,

  /** Recommendation score. */
  @SerialName(value = "_score") val score: Double? = null,
) : RecommendationsHit
