name: Tests
on: [push]
jobs:
    test:
        runs-on: macos-11
        env:
            ALGOLIA_APPLICATION_ID_1: ${{ secrets.ALGOLIA_APPLICATION_ID_1 }}
            ALGOLIA_ADMIN_KEY_1: ${{ secrets.ALGOLIA_ADMIN_KEY_1 }}
            ALGOLIA_SEARCH_KEY_1: ${{ secrets.ALGOLIA_SEARCH_KEY_1 }}
            ALGOLIA_APPLICATION_ID_2: ${{ secrets.ALGOLIA_APPLICATION_ID_2 }}
            ALGOLIA_ADMIN_KEY_2: ${{ secrets.ALGOLIA_ADMIN_KEY_2 }}
            ALGOLIA_ADMIN_ID_MCM: ${{ secrets.ALGOLIA_ADMIN_ID_MCM }}
            ALGOLIA_ADMIN_KEY_MCM: ${{ secrets.ALGOLIA_ADMIN_KEY_MCM }}
            ALGOLIA_PLACES_APP_ID: ${{ secrets.ALGOLIA_PLACES_APP_ID }}
            ALGOLIA_PLACES_KEY: ${{ secrets.ALGOLIA_PLACES_KEY }}
            ALGOLIA_ANSWERS_APP_ID: ${{ secrets.ALGOLIA_ANSWERS_APP_ID }}
            ALGOLIA_ANSWERS_KEY: ${{ secrets.ALGOLIA_ANSWERS_KEY }}
        steps:
            - name: Build project
              run: ./gradlew assemble
            - name: Run tests
              run: ./gradlew jvmTests
